### ISSUE TITLE
Refactor "Learn more" link in privacy-options.

### ISSUE THREAD

**Issue by zeraye** [duckduckgo/duckduckgo-privacy-extension#1029]
## Description
Learn more link in privacy-options is inline with text.

## Steps to Reproduce
1. Install addon on Firefox.
2. Click on "Unprotected Sites" in addon menu.

**Expected behavior:**
![screen2](https://user-images.githubusercontent.com/53649257/150649091-7da8d86b-b516-4207-acae-f432d07af1a1.png)

**Actual behavior:**
![screen1](https://user-images.githubusercontent.com/53649257/150649007-fa1e179b-8f20-4011-9274-ca9b32a18ff5.png)

**Versions**

- Extension: 2021.9.30
- Browser: Firefox Developer Edition 97.0b6 (64-bit)
- OS: Windows

## Additional information
Fix is pretty straightforward.
Example fix: https://github.com/Zeraye/duckduckgo-privacy-extension/commit/f1326d659fed80e9378be4f5f2f23e4a66aacec4

**Comment by varunmulay22** [comment]
is this an active issue?

**Comment by zeraye** [comment]
Now there is space after dot, so it can count as fix. I prefer not to close issue, but wait for someone from ddg to close it.
![image](https://user-images.githubusercontent.com/53649257/223103264-f11ebded-8d50-4ca7-9864-115c27b0df6f.png)

**Comment by imsoumya18** [comment]
I have created PR#2171 to fix this. Please review that.

**Comment by zeraye** [comment]
I'm not a ddg's developer. According to [CONTRIBUTING.md](https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/main/CONTRIBUTING.md#bug-fixes) most bug fixes and feature development are handled internally. Thus pull requests from people outside may be not reviewed.

**Comment by imsoumya18** [comment]
@zeraye I resolved this and my PR #2171 has been merged also. You can close this issue now.

**Comment by zeraye** [comment]
Issue resolved in #2171.
