### ISSUE TITLE
Too Many Console Logs

### ISSUE THREAD

**Issue by harrisonfm** [duckduckgo/duckduckgo-privacy-extension#103]
Hey, I'm running the Safari extension, but my console is getting polluted with lines from the extension "MAYBE BLOCK: file". This is coming from content-script.js. 

Is there a way to disable these? I need it clear for dev.

**Comment by jdorweiler** [comment]
This is fixed in the latest version. Try installing the extension from https://duckduckgo.com if you didn't get automatically updated.
