### ISSUE TITLE
Cannot login to unherd.com with privacy essentials enabled on firefox

### ISSUE THREAD

**Issue by lac22** [duckduckgo/duckduckgo-privacy-extension#1142]
Something changed at unherd.com about how they do logins.  Now it's a popup.  Unless I disable the addon, the popup does not pop, so I do not get to login.  I don't know if I am supposed to report this as a privacy essentials bug, or report the unherd.com site.  I cannot find a way to report the site, in any case, so I reported this here.  Thank you.

**Comment by sammacbeth** [comment]
Thanks for reporting this! I was able to reproduce the issue - this is due to our blocking of `piano.io` requests. We're working on a mitigation for this. In the meantime, you can toggle 'Site Privacy Protection' off on unherd.com from the extension popup to unbreak the site until our fix is ready.

**Comment by jonathanKingston** [comment]
@GuiltyDolphin I think the piano.io changes got resolved right?

**Comment by lac22** [comment]
In a message of Sat, 24 Sep 2022 06:05:36 -0700, Jonathan Kingston writes:
***@***.*** I think the piano.io changes got resolved right?

It's working for me now.  Thank you.

Laura Creighton

**Comment by jonathanKingston** [comment]
Thanks for confiming :)
