### ISSUE TITLE
`Error in cookie override TypeError: Failed to construct 'URL': Invalid URL` when setting cookie `path=/`

### ISSUE THREAD

**Issue by tachibana-shin** [duckduckgo/duckduckgo-privacy-extension#1161]
Hi,

I am developing an application however it seems that some DuckDuckGo cookie wrapper is not checking root urls resulting in the following error:

![image](https://user-images.githubusercontent.com/45375496/167327926-18b23f15-7225-4943-bed9-525b582fe978.png)

Even though the cookie has been set this is a nasty error

You can see line `2848` on the picture I think that's where the error is we can fix it `new URL(res[2]).hostname)` to: `new URL(res[2]. location.href).hostname`

**Comment by jonathanKingston** [comment]
@sammacbeth this code is in https://github.com/duckduckgo/content-scope-scripts/ but I think we can add a base to the constructor as mentioned. Unless these cookies should be ignored on purpose as they're same domain?
