### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by benjaminglass1** [duckduckgo/duckduckgo-privacy-extension#117]
According to [https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions](url), extension code that's written for Chrome should be easily portable to Microsoft Edge. This is further supported by the fact that Edge implements the WebExtension framework, the same API used by the newest Firefox versions. Could this extension be ported to Edge?

**Comment by alohaas** [comment]
Hey @benjaminglass1 thanks again for sharing feedback! We've received similar requests from users via other channels so it's already on our radar! We usually handle suggestions like this internally so I'll be adding yours to the list.

Thanks again!

**Comment by jonathanKingston** [comment]
So we already publish to the Edge store (https://microsoftedge.microsoft.com/addons/detail/duckduckgo-privacy-essent/caoacbimdbbljakfhgikoodekdnlcgpk) but due to Edge removing the extension heavily we don't really promote it due to poor user experience.
