### ISSUE TITLE
DuckDuckGo consider cookies on a new tab page with an iframe as third-party/can't disable ddg on new tab page

### ISSUE THREAD

**Issue by chaitanya-scio** [duckduckgo/duckduckgo-privacy-extension#1220]
## Description
Two issues:
- DuckDuckGo considers cookies on a new tab page with an iframe as third-party.
- Doesn't seem one can disable DuckDuckGo's protections on the new tab page (e.g. can't list `chrome://newtab` as unprotected)

 I've reported a broken website related to this, but I thought I could provide far more context here:

At Glean, we have a Chrome extension which also provides a new new tab page for users. This new tab page is just an iframe with our website, https://app.glean.com. When blocking third party cookies on Chrome, our cookies are still sent. However, with the latest update of DuckDuckGo's extension, our cookies don't seem to be sent anymore, logging the user out and contributing to a poor experience on every new tab. We've heard this from many users. It might be related to the changes in https://github.com/duckduckgo/duckduckgo-privacy-extension/commit/5c8a42aba1cf23e9547f4acaacdd298eb235e07c and https://github.com/duckduckgo/duckduckgo-privacy-extension/commit/11bb055c5d7316d13f03ef74a2f41d25b9ddb5f7.

- So our first question is this the expected behavior, because Chrome doesn't consider this third-party at least?
- Is there a way we can disable DuckDuckGo on the Chrome new tab page at least as a workaround?

## Steps to Reproduce

1. Have an extension with a new tab page
2. The new tab page should just be an iframe to any website that can be iframed and has login with cookies

**Expected behavior:**

The user should be logged in to the website on the new tab page.

**Actual behavior:**

The user is logged out as cookies aren't sent.

**Versions**

- Extension: 2022-05-30
- Browser:  Chrome
- OS:  Mac

**Comment by alzest** [comment]
Related: https://www.reddit.com/r/duckduckgo/comments/v2hijf/duckduckgo_privacy_essentials_extension_issue/

Also I noticed all requests to [this URL](https://connect.secure.wellsfargo.com/) have the cookies removed too and seems to impact Edge and Chrome but not Firefox. Disabling the extension or adding the domain to the list of Unprotected Sites seems to allows sites to work properly.

**Comment by SlayterDev** [comment]
Hey! Thanks for opening this issue. Our updates to cookie blocking have been a bit over zealous in identifying 3rd parties. We've shipped a fix that should alleviate most issues. In the meantime I've opened a PR to mitigate these sites and exclude them from our cookie blocking feature here: https://github.com/duckduckgo/privacy-configuration/pull/249

@chaitanya-scio I don't have an account for your product but am I right in assuming your iframe would be setting cookies from app.glean.com?

**Comment by chaitanya-scio** [comment]
Thank you so, so, so much @SlayterDev!!!!!

Fwiw, I noticed the issue still persists for us with DDG 2022.6.1 if that has fixes, so yeah giving us an exception would be very helpful.

> @chaitanya-scio I don't have an account for your product but am I right in assuming your iframe would be setting cookies from app.glean.com?

Yes – we iframe https://app.glean.com, which sends glean.com cookies to our servers. Which server depends on the user, but all of the servers are on the glean.com domain.

**Comment by chaitanya-scio** [comment]
@SlayterDev I see this is fixed for our use case so thank you so so much! I guess app.glean.com was all we needed exception-wise.

**Comment by SlayterDev** [comment]
Glad to hear!

**Comment by chaitanya-scio** [comment]
Or, sorry, correction – I think we still want to apply to all *.glean.com, because sometimes we iframe [customer].glean.com instead of app.glean.com. 

Hence perhaps https://github.com/duckduckgo/privacy-configuration/pull/252 is still valid! Mentioning in case: Not sure if reviewers need to be explicitly added to that PR, and also happy to be a reviewer if that's fine/helpful.

**Comment by chaitanya-scio** [comment]
Things still look good so I'll close out the issue! Appreciate the promptness again.

**Comment by chaitanya-scio** [comment]
@SlayterDev we got reports this started happening again today – I imagine maybe we still need the exception that was removed in https://github.com/duckduckgo/privacy-configuration/pull/253/files? Perhaps our cookie is considered a tracking one (not sure how that's classified)

**Comment by SlayterDev** [comment]
Hey @chaitanya-scio! I've opened a PR to get that exception back. We had gone through some verification to re-enable the feature but I think we haven't caught all the issues with new tab pages just yet as that's a bit tricky. Sorry for the trouble!

**Comment by chaitanya-scio** [comment]
Thank you – seems fixed!
