### ISSUE TITLE
Follow dark style preference

### ISSUE THREAD

**Issue by winkelnp** [duckduckgo/duckduckgo-privacy-extension#1223]
When the OS is put into dark mode (or `prefer-dark` for the freedesktop preference), the ddg privacy extension does not adapt to follow the dark theme, even when firefox does. Is this fixable from the extension side or is this an issue somewhere else?

**Comment by mjesusoj** [comment]
Yes, I think the extension doesn't include "dark-mode", **I hope the team add this new Feature 👏👏🚀🚀**
Also, the extension looks great!!

**Comment by jonathanKingston** [comment]
Closing in favour of #356 we have this on the timeline along with many other UI changes. Watch this space 👍🏻
