### ISSUE TITLE
Colored Icons instead of gray

### ISSUE THREAD

**Issue by MasterOfTheTiger** [duckduckgo/duckduckgo-privacy-extension#128]
It would be neat to have the popup's icon not only show the letter grade, but also a color (like in Terms of Service; Did not read). It would stand out. Since it is placed in a different place than the other extension (one in the search box itself and the other with the other extensions) having both at the same time should not be too confusing. That would be a great feature that I would really appreciate (if it is approved I might even want to try doing it).

**Comment by mdaniel** [comment]
Might I suggest creating a second issue for the "have the popup's icon not only show the letter grade" since there are two requests combined in this one. With them combined, one can't partially vote for a suggestion

**Comment by MasterOfTheTiger** [comment]
I mean a colored background for the letter instead of gray. That's all.

**Comment by alohaas** [comment]
@MasterOfTheTiger thank you for sharing your feedback. We handle issues like this internally so I'll be bringing your suggestion to the team for further consideration. You should know that one of the reasons we chose to go with grey is for accessibility. Our design team has explored other options in the past, and we've received similar feedback for our Apps so it's likely that we will revisit this decision in the future.

Thanks again!

**Comment by jonathanKingston** [comment]
As I understand it this must have been changed since this issue. Thanks for the report.
