### ISSUE TITLE
Ability to disable "Search DuckDuckGo for" in context menu

### ISSUE THREAD

**Issue by zlatin** [duckduckgo/duckduckgo-privacy-extension#13]
I have DuckDuckGo set as my default search, so I have two menu items `"Search DuckDuckGo for"` in context menu. It would be useful to have ability to disable extension in context menu.

**Comment by dharb** [comment]
Hey @zlatin, thanks for pointing this out! We just patched this (https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/86), so you'll only see one entry in the context menu when the next update goes out.
