### ISSUE TITLE
Please add ChiliPiper to allowed scripts list

### ISSUE THREAD

**Issue by reatlat** [duckduckgo/duckduckgo-privacy-extension#1425]
## Description
The [ChiliPiper](https://www.chilipiper.com/) is a marketing tool to make instant booking for a call/meeting like HubSpot meetings or any other schedulers.
DDG extension blocking it for no reason.

Please take a look to code example
- [codepen source](https://codepen.io/reatlat/pen/qBYoawQ)
- [codepen live](https://codepen.io/reatlat/live/qBYoawQ)

## Steps to Reproduce

Install latest version of extension from [Chrome Store](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg)

**Expected behavior:**
Script `https://js.chilipiper.com/marketing.js` should be loaded without any issues

**Actual behavior:**
DDG blocking script from loading, and even not show me why!

**Versions**
Latest from Chrome Store

- Extension: Latest
- Browser: Chrome and Chromium based
- OS: MacOS

**Comment by sammacbeth** [comment]
Checking against our [current blocklist](https://github.com/duckduckgo/tracker-blocklists), this script isn't being blocked by us. Are you sure the blocking was from this extesion?

**Comment by reatlat** [comment]
@sammacbeth I'm absolutely sure, I did it with fresh installed browser without cache, cookies, extensions etc...
Only one extension has been installed, it's DDG.
When it's enabled, @Chili-Piper script not loading at all.
If I do disable DDG for one page, the @Chili-Piper load as normal.

**Comment by reatlat** [comment]
@kdzwinel you're absolutely right, pages where I get loading issue with @Chili-Piper uses GTM and load it on demand after a dataLayer event on GTM.

So, basically DDG blacking any injection which may be created with GTM? Even they are not harmful?

**Comment by sammacbeth** [comment]
> So, basically DDG blacking any injection which may be created with GTM? Even they are not harmful?

We block GTM scripts as it is loaded on many sites and uses multiple Javascript APIs which are associated with tracking. This may block other legitimate scripts as a side effect. 

I'm closing this as we are not directly blocking the script in question.
