### ISSUE TITLE
AMP protection logic is brittle and breaks websites

### ISSUE THREAD

**Issue by james-trotter** [duckduckgo/duckduckgo-privacy-extension#1545]
Preface: I know this is for reporting bugs with the plugin rather than broken websites, but this issue likely affects a lot of websites.

## Description

I maintain an OIDC provider that provides login to a website, and we've been getting reports from users that they are unable to login using Firefox. Every time they submit the login form they are not recognised as authenticated and are redirected back to the initial form. After investigating we've determined that this plugin is responsible, and found that the reason it's interfering with the login flow is because of the AMP protection logic. We encode a timestamp query string parameter into our URLs, which results in a URL like this:

`https://<domain>/connect/authorize/callback?...&timestamp=...`

The AMP URL detection uses string matching against a list of keywords, and is matching it against this keyword:

https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/develop/shared/data/bundled/extension-config.json#L83

I haven't dug deep enough to understand what it does after this that breaks it, but it's clear that it's falsely detecting it as an AMP URL. I'll bet it's quite common for URLs to have a timestamp parameter that this matches on, and some of them break because of it, and they don't all have the customer volume or resources to get to the bottom of it. We've had quite a few reports from customers about not being able to login on Firefox, and none who seemed to suspect that the plugin had anything to do with it, because it works silently and doesn't indicate when it's mutating requests. Their resolution is generally to switch browsers.

**Expected behavior:**

This could be updated to require a delimiter on both sides of the 'amp' string, e.g. `/amp/`, `/amp?`. That would reduce it falsely matching against terms like 'camp' or 'amplifier'. Failing that, could an exclusion at least be added so that it doesn't treat `timestamp=` as a fingerprint of an AMP URL?

**Versions**

- Extension: 2022.10.31
- Browser: Only Firefox (the affected feature is only available on Firefox)
- OS: Any OS

**Comment by sammacbeth** [comment]
Hi @james-trotter - thanks for filing this, and sorry for breaking your site... I've opened a ticket internally and we'll try and narrow the triggering of this feature to solve the issue.

In the meantime, if you could share the site domain this is happening on, we can remotely disable the feature there, so your users won't be affected by this bug.

**Comment by james-trotter** [comment]
Hi @sammacbeth , thanks for escalating it. The affected domain is `https://identity.ibs.bankwest.com.au` - if you could add an exclusion for it that would be amazing.

**Comment by sammacbeth** [comment]
I'm going to close this as we've now disabled the deep AMP link feature that caused this.
