### ISSUE TITLE
New tracking domains

### ISSUE THREAD

**Issue by ghost** [duckduckgo/duckduckgo-privacy-extension#1598]
Hello!
There is a site called iplogger.com that allows you to create and insert a tracking pixel into any email (or even a website).

Here is a link to this service:
https://iplogger.org/tracking-pixel/

In the end, the links will look something like this:

_**Also it would be great if you will block them in Mail Protection to**_

```
iplogger[.]com/1V8mH4.jpg
iplogger[.]org/1V8mH4.jpg
iplogger[.]ru/1V8mH4.jpg
iplogger[.]co/1V8mH4.jpg
iplogger[.]info/1V8mH4.jpg
mapper[.]info/1V8mH4.jpg
2no[.]co/1V8mH4.jpg
yip[.]su/1V8mH4.jpg
iplogger[.]com/1V8mH4.jpg
ipgraber[.]ru/1V8mH4.jpg
ipgrabber[.]ru/1V8mH4.jpg
iplis[.]ru/1V8mH4.jpg
02ip[.]ru/1V8mH4.jpg
ezstat[.]ru/1V8mH4.jpg
wl[.]gl/1V8mH4.jpg
ed[.]tk/1V8mH4.jpg
bc[.]ax/1V8mH4.jpg
```

**Comment by sammacbeth** [comment]
Thanks for reporting this. Like are tracking protection in the extension, our email protection uses an automated method to detect tracking pixels in emails, so these should get automatically blocked.
