### ISSUE TITLE
Version on Safari Gallery Extension

### ISSUE THREAD

**Issue by bettinz** [duckduckgo/duckduckgo-privacy-extension#163]
Hello, I see here that latest version is 2018-3-2 (And for safari is February version).
I'm using Safari and the extension installed from safari gallery extension but the version is 2018.1.30, and I can't understand where to find latest version. Can you help me? Thanks :-)

**Comment by crgmrgn** [comment]
Seconded, if the distribution channel for the Safari extension is to be via the Apple Extension store then it must be kept current.

As of writing, 2018-3-15 is available but the "official" Safari release for users/customers is still 2018.1.30. Is DDG policy to ignore Safari users?

I can't promote adoption by organisations I advise without some consistency in deployment and versions in use …

Please resolve the version discrepancies, or if the distribution mechanism via Apple is the cause of the delays then provide a sanctioned private URL for installing/updating the Safari extension easily for users.

**Comment by bettinz** [comment]
Is this extension still supported for Safari or we need to look somewhere else? Thanks

**Comment by jdorweiler** [comment]
The latest version is always available here: https://duckduckgo.com/extensions/duckduckgo.safariextz

**Comment by bettinz** [comment]
Thank you. I can’t undestand why it isn’t on download page that link

**Comment by crgmrgn** [comment]
Please add this link to the readme.md for the project at least, it would also be sensible to add this to the extensions page on DDG, rather than link to the Apple Safari Extensions as the definitive source.

BTW, (as of 2018-04-18), the extension linked above fails to install in Safari 11.1 (macOS 10.13.4) …

**Comment by crgmrgn** [comment]
Seems we've fallen 3x releases behind in the Apple Safari Extensions website again (2018.5.24 is the latest being offered to the public) whilst 2018-7-18 is now available. 

Is there a web-hook or mechanism for auto-pushing releases into the Apple distribution channel?

**Comment by mcg** [comment]
Safari 12, just released uses a new App Store and the extension is missing completely. Safari also marks the currently installed version as having "performance problems" and disabled it.

**Comment by bartbraem** [comment]
I saw the same issue with Safari 12, any news on this?

**Comment by jdorweiler** [comment]
https://duck.co/help/add-ons/safari-12
