### ISSUE TITLE
Multiple Redirects for Different Emails

### ISSUE THREAD

**Issue by LookingForWayOut** [duckduckgo/duckduckgo-privacy-extension#1631]
Hi. I could not find a customer support email address to ask this so trying here.

I downloaded the DDG extension on my Firefox on my desktop and tried it with one of my GMAIL emails. My question is how can I try it with other GMAIL and even a DISROOT email addresses with their own DDG redirect? Do I need to have seperate Firefox profiles with their own extensions, or can I just make their own redirects without needing an extension? How do I go about making them?

Thank you.

**Comment by sammacbeth** [comment]
Hi @LookingForWayOut. You can direct any questions about email protection to [support@duck.com](mailto:support@duck.com) and someone from the team will be able to answer your questions.

**Comment by LookingForWayOut** [comment]
Thank you. I will try that address.
