### ISSUE TITLE
Cloudflare turnstile challenge blocked.

### ISSUE THREAD

**Issue by macskas** [duckduckgo/duckduckgo-privacy-extension#1648]
## Description
Cloudflare challenge (turnstile) is not working with duckduckgo privacy extenstion.
In the network logs I see url https://challenges.cloudflare.com is blocked.

## Steps to Reproduce
1) https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/
demo: [https://demo.turnstile.workers.dev/](https://demo.turnstile.workers.dev/)

**Expected behavior:**
Challenge should run just fine. Cloudflare advertise themselves more privacy friendly than google and google repcaptcha. Does very similar challenge.

**Actual behavior:**
Currently its blocked by duckduckgo extension.

**Versions**

- Extension: 2023.1.12
- Browser: Firefox (108.0.2)
- OS: Linux

## Additional Information
It might not be a bug. But it should be whitelisted, since its just a captcha to block bot/automated traffic. 

Screenshot:
![Screenshot from 2023-01-18 11-33-28](https://user-images.githubusercontent.com/7290357/213149291-9433bbe0-d399-4677-b84a-cc819d085b70.png)

**Comment by sammacbeth** [comment]
Thanks for the report - we'll look into creating a blocking exception for this.

**Comment by tiagorangel2011** [comment]
Working for me!

**Comment by macskas** [comment]
It started working for me too. I also reported this issue for Cloudflare. Don't know who fixed it but the demo page seems to be working fine.
