### ISSUE TITLE
Extension breaks in-code generated SVGs on portions of our site

### ISSUE THREAD

**Issue by PandaGnar** [duckduckgo/duckduckgo-privacy-extension#1670]
## Description
SVGs that we generate through code but don't use for tracking are deleted on our site, rendering the backgrounds of some buttons transparent. Buttons are not used for tracking -- no tracking is enabled for any student section of the site.

## Steps to Reproduce
1. Go to https://beastacademy.com/demo/school with the latest version of the extension installed on Chrome.
2. Observe that the buttons briefly render and then disappear.

**Expected behavior:**
Buttons should appear.

**Actual behavior:**
Buttons do not appear.

**Versions**
This seems to have been broken in the 2022-10-31 release, as it works in the 2022-08-xx releases.

- Extension: 2022-10-31
- Browser: Chrome
- OS: Mac OSX

## Additional Information
1. The issue happens on every version of the site.
2. I've been able to repeat this with the 10-31 release but not the 8-xx releases.

Current:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/89945219/215922934-03ed3e4f-ca43-47ed-8955-857ba337fe84.png">
Intended:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/89945219/215922989-3d41fe17-164e-4b90-9295-674f0d5d85c5.png">

**Comment by PandaGnar** [comment]
@kzar Hello! Would it be possible for the engineers at Art of Problem Solving to work on and submit a PR to fix this issue? Thank you for your time.

**Comment by laugro** [comment]
Hi @sammacbeth, we put in a workaround on the live site (an invisible sibling div for the svg) that seems to prevent the issue for users with the Duck Duck Go browser/extension, though we are not sure why this works.

There's a reproduction of the original issue (without the invisible div workaround) at this link: https://beastacademy.com/demo/school?noinvisdiv=1

**Comment by dharb** [comment]
Hi @PandaGnar and @laugro thank you for the great bug report, I really appreciate it! I was able to repro using the link you shared, and it actually surfaced a potential overmatching issue in the code we use to hide empty ad spaces. I just submitted a fix for this issue and it'll go out tomorrow.

**Comment by laugro** [comment]
Awesome, thanks for handling this so quickly!
