### ISSUE TITLE
Autofill don't work

### ISSUE THREAD

**Issue by judemont** [duckduckgo/duckduckgo-privacy-extension#1675]
## Description
The auto-completion of the search does not work in the extension.
![image](https://user-images.githubusercontent.com/96385330/216098209-4ec6e30f-bf43-492d-9343-ea398319499c.png)

**Versions**

- Extension: 2023.1.12
- Browser: Firefox 109.0
- OS: Linux, ubuntu

**Comment by sammacbeth** [comment]
The search field in the popup does not support autocomplete. You can either:
- use the autofill built into the URLbar of your browser;
- on Chrome, open a new tab and the search box there supports autocomplete;
- go directly to duckduckgo.com.
