### ISSUE TITLE
Any input field having a "data-unit" attribute is hidden in Wordpress

### ISSUE THREAD

**Issue by yoancutillas** [duckduckgo/duckduckgo-privacy-extension#1679]
## Description
Duckduckgo essentials is hiding any input having a `data-unit` attribute in any Wordpress site.

## Steps to Reproduce
1. Create a Wordpress site (default theme, no plugins)
2. Add this HTML in any page: `My field: <input type="number" data-unit="foo"/>` (in a "Custom HTML" block)
3. View the page (here is an example: https://test.booking-activities.fr/sample-page/)

**Expected behavior:**
Input field should be displayed

**Actual behavior:**
Input field is being hidden if DuckDuckGo Privacy essentials is active

**Versions**
- Extension: 2023.1.12
- Browser: Firefox
- OS: Windows 10

**Comment by sammacbeth** [comment]
Thanks for the report. This looks like a false positive from our 'element-hiding' feature. I'll open an issue internally for this.

**Comment by yoancutillas** [comment]
Thank you!

**Comment by sammacbeth** [comment]
We've updated the config so this should be resolved for all users now. We're going to follow up with improvements to the feature to prevent matching `input` elements incorrectly.
