### ISSUE TITLE
Performance issue on init

### ISSUE THREAD

**Issue by tborychowski** [duckduckgo/duckduckgo-privacy-extension#169]
Hi,

I've noticed a performance issue with this extension in Firefox.
(Firefox 60b3, macos high sierra)

When it's enabled and I start Firefox it freezes the window for 2-3 seconds.
I've noticed that the same happens when I'm in "Addons" and toggle the extension (enable/disable).
It seems that when it's initialised - it's doing some heavy stuff...

**Comment by 2green2freak** [comment]
Having the same issue, Firefox is very unresponsive when started, when the plugin is enabled. It needs more than 5 seconds before I'm able to switch or close tabs etc.
