### ISSUE TITLE
Searchspring Components blocked by DuckDuckGo Privacy

### ISSUE THREAD

**Issue by julesbravo** [duckduckgo/duckduckgo-privacy-extension#1709]
## Description
Some of our clients has reported that several of their customers have complained that they are not seeing products load on their search and category pages. This appears to be isolated to customers with the DuckDuckGo Privacy browser extension installed in their browser. The extension is blocking our JavaScript bundle from loading on the page which in return means no results are displayed on theses pages. What can be done about this? Thanks in advance!

## Steps to Reproduce
1. Install DuckDuckGo Privacy Extenstion
2. Visit a [search](https://www.madetrade.com/collections/shop?q=towels) or [category](https://www.madetrade.com/collections/table-linens) page powered by Searchspring.
3. Verify no results are displayed.

**Expected behavior:**
Results will display as normal as they would with the extension disabled.

**Actual behavior:**
No results are displayed.

**Versions**
- Extension: 2023.1.12
- Browser: Tested on Firefox, but likely affects all browsers with extension.
- OS: Tested on Mac, but likely affects all operating systems with extension.

## Additional Information
It appears our bundle.js was added to your blocklist as part of your [January 2023 web blocklists update](https://github.com/duckduckgo/tracker-blocklists/commit/4ee1efe9aff566339710cc1e6fa2040460042cd2).

![image](https://user-images.githubusercontent.com/194692/217263278-612aa7a2-a7f6-428a-83a1-def22bd38032.png)

**Comment by sammacbeth** [comment]
Thanks for reporting. We've noted this issue in https://github.com/duckduckgo/privacy-configuration/pull/663 and just shipped an exception to our blocklist to allow this script. This should start working again shortly.

**Comment by julesbravo** [comment]
Thanks @sammacbeth 

<img src="https://media3.giphy.com/media/joeRYmOkLaj2U6hwdj/giphy.gif"/>

**Comment by julesbravo** [comment]
@sammacbeth It looks like were also seeing this on the Safari extension. Is that a separate repo we'd need to create an issue for?
