### ISSUE TITLE
Feedbro RSS Reader extensions can't load youtube RSS feeds if DuckDuckGo Privacy Extensions are enabled

### ISSUE THREAD

**Issue by NinjaSciurus** [duckduckgo/duckduckgo-privacy-extension#1732]
## Description
The Feedbro Reader is an RSS reader extension. All Youtube channel RSS feed requests issued by Feedbro are blocked by the DuckDuckGo Privacy Extension, they never even hit the network layer. Disabling the DuckDuckGo Privacy Essentials extensions immediately enables Feedbro to load youtube channel RSS feeds.

## Steps to Reproduce

1. Install and activate DuckDuckGo Privacy Extensions
2. Install and activate Feedbro Reader extension
3. Try to register a Youtube Channel's RSS feed url in Feedbro and use the "Load" button in the "Add a new feed" dialog to load the Channel title. An error message appears static that the url is invalid.
4. Replay the XMLHttpRequest on the browser console in the tab with Feedbro loaded to create an entry in the F12 tools "Network" tab:
```
var j = new XMLHttpRequest()
j.open("GET", "https://www.youtube.com/feeds/videos.xml?channel_id=UC3XTzVzaHQEd30rQbuvCtTQ", true)
j.send()
```
5. Observe the console result: `GET https://www.youtube.com/feeds/videos.xml?channel_id=UC3XTzVzaHQEd30rQbuvCtTQ net::ERR_BLOCKED_BY_CLIENT`

**Expected behavior:**
The youtube channel feed xml gets loaded via XMLHttpRequest and is usable by the Feedbro extension.

**Actual behavior:**
The XMLHttpRequest is blocked. Replaying the request on the browser console shows the error `net::ERR_BLOCKED_BY_CLIENT`

**Versions**

- Extension: 2023-02-16
- Browser: Microsoft Edge Version 109.0.1518.78 (Official build) (64-bit) 
- OS: Windows 

## Additional Information
The issue is repeatable every time, even after reinstallation of both (!) extensions, browser relaunch and computer reboot.

**Comment by sammacbeth** [comment]
Thanks for the report. I was able to reproduce the issue with the Manifest V3 version of our extension, but not with MV2. It therefore looks like the new Chrome APIs for blocking requests allow blocking of requests from other extensions (previously this wasn't possible), which is what is causing this issue.

To fix your issue for the time-being, could you try installing the version of the extension from the [Chrome Web Store](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg) (instead of the Edge extension store), as that version still uses the old MV2 APIs. I'll also look into a fix on our end.

**Comment by NinjaSciurus** [comment]
Thanks for looking into the issue. I can confirm that the extension from 
the Chrome Web Store doesn indeed work as expected.

If you need any more input/info, let me now. Again thanks for your 
assistance!

On 23.02.2023 17:49, Sam Macbeth wrote:

> Thanks for the report. I was able to reproduce the issue with the 
> Manifest V3 version of our extension, but not with MV2. It therefore 
> looks like the new Chrome APIs for blocking requests allow blocki
> 
> DuckDuckGo removed 1 tracker.
> 
> More →
> 
> Thanks for the report. I was able to reproduce the issue with the 
> Manifest V3 version of our extension, but not with MV2. It therefore 
> looks like the new Chrome APIs for blocking requests allow blocking of 
> requests from other extensions (previously this wasn't possible), which 
> is what is causing this issue.
> 
> To fix your issue for the time-being, could you try installing the 
> version of the extension from the Chrome Web Store [1] (instead of the 
> Edge extension store), as that version still uses the old MV2 APIs. 
> I'll also look into a fix on our end.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg
[2] 
https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/1732#issuecomment-1442104081
[3]
