### ISSUE TITLE
autofill.js > inferInputType freezing page with heavy html content

### ISSUE THREAD

**Issue by jlcd** [duckduckgo/duckduckgo-privacy-extension#1792]
## Description

I have a localhost page that generates a 12.5k lines html content, with a bunch of inputs. When the Chrome extension is enabled (doesn't matter if ignoring the localhost domain or not), the pages freezes for around 12s before allowing me to click around.

By turning on the console's Performance Insights, I was able to pinpoint the cause to the Duckduckgo extension:
![image](https://user-images.githubusercontent.com/232178/225154103-c04d96af-453f-4e9f-8e38-dff333144cb1.png)

## Steps to Reproduce

1. Install the Duckduckgo Privacy Essentials extension on Chrome
2. Load a html page with a lot of lines and inputs
3. You won't be able to click around for a good while

**Expected behavior:**

Be able to use the page right away despite having the extension enabled.

**Actual behavior:**

The page freezes for a long time.

**Versions**

- Extension: 2023.3.3
- Browser: Chrome
- OS: Windows

## Additional Information

Happens every time and took me a week to identify it wasn't on my app. After I did a bunch of performance improvements, noticed it wasn't on my side. Oops.

**Comment by sammacbeth** [comment]
We've now released this changes, so the performance issues with autofill should largely be solved. Please re-open if you continue to see performance issues.
