### ISSUE TITLE
Localhost:8080 freezes until DDG extension stopped

### ISSUE THREAD

**Issue by qskousen** [duckduckgo/duckduckgo-privacy-extension#1817]
## Description
Navigating to a certain localhost:8080 page causes the page to become unresponsive until Firefox reports that the DDG extension is slowing down the browser and gives me an option to stop it. Stopping it fixes the slowdown. I have captured a performance profile:
https://profiler.firefox.com/public/1rns1z2dwrmf127p2meyp3hpfmtn24wepshre78/calltree/?globalTrackOrder=01&implementation=js&thread=1&v=8

if I add a mapping for `127.0.0.1    some.domain` in my hosts file and access the site using that instead of localhost, DDG does not lock up the page.

## Steps to Reproduce

I am not sure yet how this can be reproducible without the code that I am running on my website. It is a pretty plain Laravel 10 website displaying a Filament resource table.

**Expected behavior:**

The page would be responsive and DDG extension would not be operating on a localhost domain.

**Actual behavior:**

The page loads, but becomes unresponsive until FF prompts to stop the DDG extension.

**Versions**

- Extension: 2023.3.15.1
- Browser: Firefox 111.0
- OS: Linux 

## Additional Information

The issue is repeatable on the page with the table. Other pages do not have the same problem.
Happy to provide any additional info that I can.

**Comment by sammacbeth** [comment]
Thanks for the report @qskousen. This is a known performance issue with our email autofill script, and the trace confirms that. We have a fix ready for that, which we will be releasing next week.

**Comment by sammacbeth** [comment]
This release now went out. Would you mind checking if the issue is resolved for you now?
