### ISSUE TITLE
error while inserting image on substack

### ISSUE THREAD

**Issue by srsudar** [duckduckgo/duckduckgo-privacy-extension#1841]
## Description

This is a weird issue, and I haven't been able to track it down. I've isolated it to a single commit, and I still can't figure it out.

If you're on a substack post and you insert an image, you get an alert saying there was a network issue, please try again. This is a red herring--it is in fact something the duck duck go extension is doing or causing. If you disable the extension, you can insert an image.

I've spent some time debugging, and the difference seems to be stemming from something deep in the site's code, where with the extension something is a doubly nested array--`[ [ 'picture' ] ]`--while without the extension it is `[ 'picture' ]`.

I've built the extension at version [`2023.3.3`](https://github.com/duckduckgo/duckduckgo-privacy-extension/releases/tag/2023.3.3) and do not have the problem.

The problem was introduced in [`2023.3.15`](https://github.com/duckduckgo/duckduckgo-privacy-extension/releases/tag/2023.3.15). I've bisected between the two versions and it is [the prepare release commit](https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/1798/files) where the problem begins. Bizarrely, on that commit I can fix it by changing the version in the chrome manifest to something like `2023.3.10`. Reverting the other changes didn't seem to help. Maybe the extension does some network request based on the version or something?

## Steps to Reproduce

1. install the current extension
2. go to a substack (make one if you need to) and create a post
3. click the insert image button (see screenshot--also see that it's blocking some datadog requests--perhaps something here is to blame?)
    * <img width="1493" alt="image" src="https://user-images.githubusercontent.com/6362625/228675021-32c0714b-60ab-4f68-838d-430d22918ea4.png">
4. Upload an image and see the network error message. (Again, though, it's not actually a network error as far as I can tell--not seeing anything blocked.)

**Expected behavior:**

You can insert an image

**Actual behavior:**

The site claims there was a network error, although as far as I can tell there wasn't (it's a try/catch that expects only network problems).

**Versions**

- Extension: 2023.3.28.1, though afaict it was introduced in 2023.3.15
- Browser: Chrome stable
- OS: Mac

## Additional Information

Provide additional context (optional):
1. Is the issue repeatable or intermittent? **repeatable**
3. Did this issue start after an upgrade to a new extension version? If so, can you repeat it using a pervious extension version? **introduced in a particular commit, though I don't understand how**
4. Are there any errors in the extension debugging console? **yes, blocking cloudflare insights and datadog**
5. Include screenshots if they're helpful. **see above**

**Comment by jonathanKingston** [comment]
Hey cheers for the detailed report here.

I've exempted this domain for now and will fix this up: https://github.com/duckduckgo/privacy-configuration/pull/804

It seems substack are sending `['picture']` to `createElement` via a library which was making our code throw: https://github.com/duckduckgo/content-scope-scripts/pull/379

**Comment by srsudar** [comment]
Very interesting. The weird thing to me was that by the time we found the function call in the library, it seemed as if the actual args had changed somehow. There was some prosemirror/tiptap (the editing library) that got `'picture'` without the extension on, but `[ 'picture' ]` with the extension on. I couldn't figure out what duckduckgo was changing to get to that point.

I also couldn't figure out why the version change was what led to the problem. Does the script do some runtime check that, based on version, pulls in different scripts to execute?

**Comment by ktusznio** [comment]
Hi @jonathanKingston! Appreciate your response here and the whitelisting of the Substack domain! 🙌 That's super helpful to us. However, a lot of publications running on Substack operate under custom domains and so they will still be impacted if their writers use the DDG extension - of which I'm a big fan, btw. Thanks for your help with this!

**Comment by jonathanKingston** [comment]
> I also couldn't figure out why the version change was what led to the problem. 

We scope the change mentioned to a certain release.

> However, a lot of publications running on Substack operate under custom domains and so they will still be impacted if their writers use the DDG extension.

Do they load the same third party web requests? IE is there a common URL that they load or is this also from their domains.

We're likely to roll out the changes pretty quickly to extension users in the coming week.

**Comment by ktusznio** [comment]
@jonathanKingston yes, I should have mentioned originally: all of our assets load from substackcdn.com 👍

**Comment by jonathanKingston** [comment]
@ktusznio all the custom domains should now work too, thanks for confirming they use that domain :).

We'll be rolling out the real fix this week but now it's less of a rush :)

**Comment by ktusznio** [comment]
Awesome. We really appreciate the quick fix!
