### ISSUE TITLE
getImageData CreateJS Lib - Canvas based apps…

### ISSUE THREAD

**Issue by albowler** [duckduckgo/duckduckgo-privacy-extension#1927]
Hi,

We run a couple of sites that our users have been complaining that the canvas based apps are not functioning correctly, when we've looked into it - it appears that the duckduckgo privacy extension is causing issues when a canvas element uses getImageData.

The extension is not showing any errors in the console, but we have confirmed the extension is causing the issue by simply enabling/disabling it.

We use the CreateJS libraries for our apps - and it is the library itself that is using getImageData on the initialization of the canvas, so this means any site using the library will be affected by the duckduckgo extension issue.
 
## Steps to Reproduce

1. Enable DuckDuckGo Privacy Extension.
2. Visit: https://www.online-stopwatch.com/duck-race/full-screen/
3. Click "SET" to load the race.
4. Click "START". The race will not work or load correctly.

**Expected behavior:**

1. Disable DuckDuckGo Privacy Extension.
2. Visit: https://www.online-stopwatch.com/duck-race/full-screen/
3. Click "SET" to load the race.
4. Click "START" to start the race. The race will run.

**Versions**

Latest chrome version installed today.

## Additional Information

A lot of schools (our main users) have the DuckDuckGo extension installed, so this is now affecting a lot of ours.

Would it be possible to add our sites: https://www.online-stopwatch.com/  and https://www.online-calculator.com/ to your whitelist/allow lists until the bug is resolved? 

Thank you for your help!

**Comment by dharb** [comment]
Hey @albowler thanks for the detailed report! Sorry about the trouble, it looks like our anti canvas fingerprinting feature is the culprit. I'll get a mitigation out for this shortly.

**Comment by dharb** [comment]
Hi @albowler, we've now shipped a mitigation for this issue and its had a chance to roll out to all users, so the issue should be entirely resolved. Thanks again for the report!
