### ISSUE TITLE
Extension slows down github.com navigation

### ISSUE THREAD

**Issue by hugocaillard** [duckduckgo/duckduckgo-privacy-extension#1929]
## Description
I noticed that the DuckDuckGo Privacy Essentials extensions slows down navigation on github.com. To the point where I disabled the extension

## Steps to Reproduce

1. Go to a PR on github.com
2. Go to the "files changed" tab
3. Go back and forth between the "discussion" and "files changed" tab
4. You should experience slowness

Disable the extension: back to normal.

**Expected behavior:**

Should not slowdown websites

**Actual behavior:**

Slow navigation on github.com

**Versions**

- Extension: 2023.4.11
- Browser: Firefox 112.0.2 64-bit
- OS: mac os ventura 13.3.1

## Additional Information
It looks like bitwarden had more or less similar issues https://github.com/bitwarden/clients/issues/2277. Not sure it helps

**Comment by AlexandreBrg** [comment]
I through it was related to new firefox versions, but it was indeed this extension which was slowing down (pretty heavily) browsing on github.

**Comment by hugocaillard** [comment]
Looking good! thanks for the fix 🔥
