### ISSUE TITLE
Cannot reactivate email address once deactivated

### ISSUE THREAD

**Issue by gerardbosch** [duckduckgo/duckduckgo-privacy-extension#1976]
## Description

Hi there!

Once you have deactivated a private random address through the link on the banner of the mail, it seems to be no way to enable it again once you close the deactivation page and you deleted the email that contained the link to go to that page.

I found that in case you keep the original mail, you can click again to the banner link "More —>" and in that case si managed to reactivate the address, even though the button still shows "Deactivate". But if you go ahead and try to deactivate an already deactivated mail, you head to the page with the button to "Reactivate This Address".

The following shows for already deactivated addresses:
![image](https://github.com/duckduckgo/duckduckgo-privacy-extension/assets/30733556/49ef6f80-1a39-4304-8f1c-d675773205cd)

I see a few problems here:

1. The most important is that if you deleted the original email, I couldn't find any way to enable the address back. Maybe a address management page is missing somewhere?
2. The second is that none of the above flow that would allow to enable it back looks obvious or intuitive.

## Steps to Reproduce

1. Click the "More —>" link on the email banner to view the info and manage the duck address.
2. Click on "Deactivate"
3. Close the tab
4. Delete the email
5. Empty the inbox trash
6. No way to enable the address back (unless I'm not finding it).

I hope this issue belongs to this repo, let me know or feel free to move it if necessary. Cheers!

**Comment by sammacbeth** [comment]
Thanks for the report. I raised this with the email team, and this is a known issue which we'll try and address.
