### ISSUE TITLE
Join Request duckduckgo

### ISSUE THREAD

**Issue by HassanUsman** [duckduckgo/duckduckgo-privacy-extension#2]
Hi, could you invite me to the duckduckgo GitHub organization?

**Comment by nunesdaniel** [comment]
Hi, I would like to join duckduckgo GitHub organization and Contribute to it.

**Comment by nileshgulia1** [comment]
please add issues ..:)

**Comment by tagawa** [comment]
Hi @HassanUsman and @nunesdaniel 
Thank you for wanting to help out! We're not accepting new members of the DuckDuckGo GitHub organization at present (please see the message at https://duckduckhack.com for the current status) but you're very welcome to file issues for the browser extension here.
