### ISSUE TITLE
CSS Injection

### ISSUE THREAD

**Issue by ghost** [duckduckgo/duckduckgo-privacy-extension#2003]
I noticed the ext was injecting some css
![image](https://github.com/duckduckgo/privacy-configuration/assets/89495053/94f22857-3be4-494c-8a32-ce17bb7b14c6)
All of those spaces result in a giant string
![image](https://github.com/duckduckgo/privacy-configuration/assets/89495053/6a04dff9-36c9-4e2a-ae4c-2ed1546449d5)
And I guess this would just be a slight QOL fix?
It could simply just be
![image](https://github.com/duckduckgo/privacy-configuration/assets/89495053/79d656dd-ce16-4317-a5e6-dae1f5d99731)
And work fine.
![image](https://github.com/duckduckgo/privacy-configuration/assets/89495053/d576ea6f-543d-410a-ac67-94d62108c922)

**Comment by sammacbeth** [comment]
This should be resolve now the runtime checks feature is disabled.
