### ISSUE TITLE
Panomax webcams not loading

### ISSUE THREAD

**Issue by nhelminger** [duckduckgo/duckduckgo-privacy-extension#2007]
## Description
The extension does not load our webcams. Only the grey background is visible.

## Steps to Reproduce
1. activate the extension DuckDuckGo Privacy Essentials
2. load the page https://rio.panomax.com/sugarloaf
3. only a grey background is visible
![image](https://github.com/duckduckgo/duckduckgo-privacy-extension/assets/134626147/91263950-525f-48a8-942f-f64381ff4c69)
4. deactivate the extension
5. the whole content of the page is visible
![image](https://github.com/duckduckgo/duckduckgo-privacy-extension/assets/134626147/f3801d44-a8a7-4002-9a9b-2437f418f5cb)

**Expected behavior:**
The whole content of the page should be visible.

**Actual behavior:**
Only the gey background is visible.

**Versions**
- Extension: 2023.5.9
- Browser: Firefox
- OS: Windows

## Additional Information
The issue is repeatable for every of our 700 cameras. So none of them is visible when the extension is activated.
We have 5 millions view a month. So there are quite a lot of users reporting these problems to us.

**Comment by sammacbeth** [comment]
Looks like this is caused by the `runtimeChecks` protection. cc @jonathanKingston 

We'll get a mitigation for this out to fix this for your users.
