### ISSUE TITLE
broken site: https://www.bbc.co.uk/iplayer

### ISSUE THREAD

**Issue by mattjburrows** [duckduckgo/duckduckgo-privacy-extension#207]
## Which website is broken? (copy and paste the URL):
iPlayer playback pages do not play content when the user has the safari plugin installed.

The play button displays a continuous spinner and the user is unable to click it to play content An example of a page that is broken is - https://www.bbc.co.uk/iplayer/episode/b0b09dss/stephen-the-murder-that-changed-a-nation-series-1-1-the-loss-of-joy

## Describe the issue. (What's breaking on the page? Attach a screenshot if possible):

When the page loads we fetch a script to allow us to bucket users into A/B tests.

For cases where a privacy plugin is installed we simply catch errors and continue to load the player and other page content. For some reason the request never fulfills or fails and after 30 seconds times out with the plugin enabled on Safari.

Go to iPlayer playback pages do not play content when the user has the safari plugin installed. The play button displays a continuous spinner and the user is unable to click it to play content An example of a page that is broken is - https://www.bbc.co.uk/iplayer/episode/b0b09dss/stephen-the-murder-that-changed-a-nation-series-1-1-the-loss-of-joy
Observe that the spinner continously spins

When disabling the DuckDuckGo add-on in Safari, the spinner turns to a play button and users can play content.

**Page with the extension disabled showing the request for the file:**

<img width="1440" alt="screen shot 2018-04-19 at 11 23 13" src="https://user-images.githubusercontent.com/1158470/38987635-5befb1a8-43c8-11e8-8d9f-2be68400f8dc.png">

**Page with the extension enabled showing the request is never made:**

<img width="1440" alt="screen shot 2018-04-19 at 11 23 36" src="https://user-images.githubusercontent.com/1158470/38987634-5bc7a01e-43c8-11e8-9511-49854a53b9c3.png">

**Comment by dharb** [comment]
Hey @mattjburrows, thanks for letting us know! We've identified the issue that was causing the breakage. A fix will be included in our next release, which is going out in a few days. 

It might take a little longer for users who installed the extension through Apple's Extension Gallery to receive the update, but rest assured it's on its way.

**Comment by mattjburrows** [comment]
@dharb thanks for the quick reply! Do you have any details on what the issue was and how you are resolving it?

**Comment by dharb** [comment]
@mattjburrows there's a rule in the EasyPrivacy list that was causing us to identify your optimizely script as a tracker and block the request, which seems to have broken the player in safari only.

See https://github.com/easylist/easylist/blob/0a6c6cfce3dda4f374c62ee7458848ed29bb27d3/easyprivacy/easyprivacy_general.txt#L2171

**Comment by brindy** [comment]
Hi folks,

Things have moved on a bit since this was last updated.  

We have a new extension for Safari that uses Tracker Radar and you can install it from the App Store: 
https://apps.apple.com/us/app/duckduckgo-privacy-essentials/id1482920575?mt=12

You can find the code for it here:
https://github.com/duckduckgo/privacy-essentials-safari

Thanks!
