### ISSUE TITLE
Medium-to-High Energy Impact in Firefox on Linux

### ISSUE THREAD

**Issue by BarryManifold** [duckduckgo/duckduckgo-privacy-extension#2077]
## Description

The DuckDuckGo Privacy Essentials extension for `Firefox 114.0.1 (64-bit)` consistently has
a medium-to-high energy impact as reported in the `about:performance` page.
## Steps to Reproduce

1. Type `about:performance` in browser;
2. press enter; and
3. monitor the `energy impact` column for this extension.

**Expected behavior:**

I expect this extension to almost never have an energy impact above low.
Ublock Origin does a tremendous job at this, so it's certainly possible for
this extension to achieve very similar energy-impact characteristics.
**Actual behavior:**

Firefox consistently reports that this extension has a medium-to-high energy impact.
**Versions**

- Extension: 2023.7.7.2
- Browser: Firefox (64 bit)
- OS: Linux

**Comment by sammacbeth** [comment]
Thanks for this report. We recently shipped a performance improvement to our content-script, which is now available in the latest (`2023.9.20`) version. Please let us know if you're still observing these warnings after that update.
