### ISSUE TITLE
Turn on Energy Saver even when plugged in 

### ISSUE THREAD

**Issue by trimechee** [duckduckgo/duckduckgo-privacy-extension#2099]
Hello, thank you for this wonderful awesome extension and for the new Duckduckgo web browser for windows ! 💯 🥇 

i can't find the github page of Duckduckgo web browser so i post here : please i have request : 

sadly energy saver doesn't work when plugged in, my notebook is not very powerful and the battery can get tired...it will be great to add option to enable permanently energy saver even when plugged in the new Duckduckgo web browser, thank you so much !

https://support.google.com/chrome/answer/12929150?visit_id=638227751357191071-2548025678&p=chrome_memory_saver&rd=1#memory_saver&zippy=%2Cturn-memory-saver-on-or-off%2Cturn-energy-saver-on-or-off

**Comment by sammacbeth** [comment]
I've raised this issue internally with our Windows team and will update here if I hear back from them.

**Comment by trimechee** [comment]
Amazing awesome !!! Thank you so much @sammacbeth :) 💯 🥇

**Comment by trimechee** [comment]
Hello Mr @sammacbeth , thank you so much again for your precious great help and great generosity and kindness :) 🥇 💯 

Please without wanting to tire you, I have another request please  : transmit also to the mangnifque Windows team  of the awesome Duckduckgo Browser this new request which is important to me and many people and allow  to differentiate  and stand out even more from the other competitors with these revolutionary new features that save energy, battery and SSD !! Thank you very much :) 

https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/2247#issue-1913229395

**Comment by sammacbeth** [comment]
Thanks, the other issue has also been filed with the team. I'm going to close these issues for now, as they're not related to the browser extension.

**Comment by trimechee** [comment]
Great ! Thank you so much :) we understand, You're right  related to the browser extension :) 
I searched but I didn't find the Duckduckgo web browser github page, that's why I made my requests here, there is not a github page for the new Duckduckgo web browser for windows please ?

**Comment by trimechee** [comment]
Excuse me Mr @sammacbeth ,  last request please:)  the addons /extensions on the chrome store are prohibited from downloading from youtube, and also there may also be other extensions banned from the chrome store but allowed on the microsoft edge store, it will be great to pass on too to the Duckduckgo team the suggestion to add support for edge browser store, or opera browser store and may be also firefox browser store....thank you so much :)
