### ISSUE TITLE
Safari toolbar button doesn't look right

### ISSUE THREAD

**Issue by gpderegil** [duckduckgo/duckduckgo-privacy-extension#222]
What's the issue?
The toolbar button for the extension in Safari used to look adequately sized and changed hue depending on the grade assigned to the website. For the past 2 or 3 versions (the last version that I could find that still looks correctly is 2018.2.7) the button has no longer changed hue, instead always looking the same shade of gray, and the aspect ratio is completely wrong in comparison to other safari extensions and stock toolbar buttons (the grade is too large for the button).

Attached you'll find four screenshots illustrating the problem, comparing not only the size but how the hues used to change. I'm filling this as a bug since I assume not fitting with the design language even though it previously did, and loosing functionality is probably a bug.
In both cases, old and new, the DuckDuckGo logo that appears when a website is not graded, or when on the new tab bar, looks correctly in both size and hue.

DuckDuckGo Logo
(This one looks the same in all versions)
![dlogo](https://user-images.githubusercontent.com/36803825/40330461-ce8d9e58-5d01-11e8-972b-14fbc2e8de21.png)

Old Look
(Notice the change in hue, and the correct size in comparison to uBlock Origin and the stock buttons)

![dold](https://user-images.githubusercontent.com/36803825/40330277-49c1076e-5d01-11e8-8a2d-423500061341.png)
![gold](https://user-images.githubusercontent.com/36803825/40330282-4ec4aae0-5d01-11e8-85fe-4a64342476aa.png)

New Look
(Notice no change in hue and disproportionate size of the grade)
![dnew](https://user-images.githubusercontent.com/36803825/40330329-77670e34-5d01-11e8-9f25-f4ddbbe24258.png)
![gnew](https://user-images.githubusercontent.com/36803825/40330335-7adde4f2-5d01-11e8-880c-c3db968fd4c4.png)

**Comment by cmnstmntmn** [comment]
indeed i also notice that the size is a bit bigger;

https://github.com/duckduckgo/duckduckgo/issues/268

**Comment by brindy** [comment]
Hi, we have a new extension for Safari which you can install from the App Store: 
https://apps.apple.com/us/app/duckduckgo-privacy-essentials/id1482920575?mt=12

You can find the code for it here:
https://github.com/duckduckgo/privacy-essentials-safari

Thanks!
