### ISSUE TITLE
"The page isn’t redirecting properly" when searching on DDG

### ISSUE THREAD

**Issue by kreatinbiceps** [duckduckgo/duckduckgo-privacy-extension#2242]
## Description

Using the extension breaks duckduckgo.com, resulting in "The page isn’t redirecting properly" on every search.
When disabling the extension the search works as normal.

## Steps to Reproduce

1. Have DuckDuckGo Privacy Essentials enabled
2. Search on duckduckgo.com 

**Expected behavior:**
Showing search results

**Actual behavior:**
Error messsage:

```
The page isn’t redirecting properly

LibreWolf has detected that the server is redirecting the request for this address in a way that will never complete.

This problem can sometimes be caused by disabling or refusing to accept cookies.

```
**Versions**
- Extension: 2023.9.1
- Browser: LibreWolf 117.0.1-1
- OS: Linux

## Additional Information

Extension debugging console screenshot when searching on ddg:
![image](https://github.com/duckduckgo/duckduckgo-privacy-extension/assets/58094411/7835e2e8-4ab6-4f21-a0a5-80d416d8e6b7)

**Comment by VaporMoon** [comment]
Experiencing the same issue in Firefox 117.0.1 on Windows 11.

**Comment by twolodzko** [comment]
Same here. Your extension breaks using your own search...

**Comment by sammacbeth** [comment]
Thanks for bringing this to our attention. This is a conflict with some Adblocking extensions, which are trying to remove a URL parameter that our extension adds to search queries. The rule in question is in the "Adguard URL Tracking protection" filter list, and they have already updated their list to remove the entry: https://github.com/AdguardTeam/AdguardFilters/issues/161751#issuecomment-1732554154. That comment contains a workaround to fix the problem with your adblocker until the updated filter list is available.
