### ISSUE TITLE
New Tab is too slow to open

### ISSUE THREAD

**Issue by afterwind-io** [duckduckgo/duckduckgo-privacy-extension#2412]
## Description

DDG overrides the new tab page with its own customized page, but it is slow to open.

## Steps to Reproduce

1. Open a new tab

**Expected behavior:**

Show the full page in decent speed.

**Actual behavior:**

Slow loading (Usually slow, and various, see below)

**Versions**

- Extension: 2023.12.6
- Browser: Chrome
- OS: Mac

## Additional Information

I did some researches and found that when opening the new tab, it first connects to https://duckduckgo.com/chrome_newtab?atb=xxx, then loads all resources and shows the page. The problem is, due to some reasons, I have a slow connection to the DDG website, thus causes slow to extremely slow loading of the new tab, and it is pretty disturbing.

So is it technically possible to load an local copy of the new-tab page, or can we have a switch to turn off the new-tab-page override?

**Comment by sammacbeth** [comment]
The new tab page is not something that this extension sets - it's a side effect of how Chrome handles the default search engine. When you set DuckDuckGo as the default search engine, your new tab page is updated to the DuckDuckGo new tab page. You can change the new tab page in Chrome by installing a new tab page extension, or changing it from the Chrome settings.
