### ISSUE TITLE
Search gets fixated on a single word, ignores context, or prioritizes advertisments and quantity of results

### ISSUE THREAD

**Issue by Kiwiroo** [duckduckgo/duckduckgo-privacy-extension#2434]
## Description
Often the search will get fixated on a single word in my search terms, or exclude context words as a suggestion, this is seemingly to give "more" search results, which I feel undermines the goal of searching generally, which is to narrow down results.
Sometimes shows itself as" X had a few results, showing results for Z instead, which has more results than you could read in a lifetime"

## Steps to Reproduce

1. Search for "how to get rid of my phone for good"

**Expected behavior:**

Results on how to live phone free, how to stop using a phone, advice on chucking a phone off a bridge and things like that.

**Actual behavior:**

The term "phone" quietly gets swapped for "old phone", and i am given ways of "disposing" of a phone, and disturbingly, ads for new phones

**Versions**
Reliably fails on all versions

- Extension: 20xx-xx-xx
- Browser: 
- OS:

**Comment by sammacbeth** [comment]
Thanks for your report @Kiwiroo - unfortunately, this repo is just for the browser extension and not for search. You're best filing this through our feedback tool on the search results page (there's a 'Share feedback' button in the bottom-right corner of the page).
