### ISSUE TITLE
"Tracker Networks Top Offenders" section semantically comes before the site details 📄

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/duckduckgo-privacy-extension#250]
"Tracker Networks Top Offenders" semantically comes before the details of the site. I suspect this part is not as important so it might be better to move the markup below `.site-info`.

<img width="1680" alt="tracker-network" src="https://user-images.githubusercontent.com/81969/43589922-bf7e09e6-963d-11e8-9d0e-af2067600ae6.png">

**Comment by andrey-p** [comment]
This one has been bugging me so much.

**Comment by sammacbeth** [comment]
I believe this was resolved by #489
