### ISSUE TITLE
Enhancement text is being read in a weird way 🤪

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/duckduckgo-privacy-extension#254]
Investigate why enhancement from D to B is not being read properly. VoiceOver is not pronouncing "TO" properly.

<img width="1680" alt="" src="https://user-images.githubusercontent.com/81969/43590234-84139d5c-963e-11e8-8feb-a7cf1ec33e74.png">

**Comment by andrey-p** [comment]
Fixed in #278.
