### ISSUE TITLE
Text should not have a heading tag if it's not a heading 🛀

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/duckduckgo-privacy-extension#255]
'Forced Encryption' probably shouldn't be h2 reading it using a screen reader doesn't sound right. It's not the start of a section.

<img width="1680" alt="" src="https://user-images.githubusercontent.com/81969/43590334-c02bb716-963e-11e8-82c4-90a82ecfe12e.png">

**Comment by vladhnat** [comment]
Hi 👋
I wanna contribute to this project and it would be great if this issue will be one of the first my contribution. 🎉
What the status of this issue❓
If the status is still the same then how can I assign it to myself and take it to the work❓
Thanks 🙂

**Comment by kdzwinel** [comment]
This was fixed by https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/346. Thank y'all!
