### ISSUE TITLE
Blocks WGU's important course sidebar

### ISSUE THREAD

**Issue by noerrorsfound** [duckduckgo/duckduckgo-privacy-extension#297]
It looks like DuckDuckGo blocks the sidebar of WGU courses. The sidebar's URL looks like this:
https://srm--c.na60.visual.force.com/apex/CommonsSidebar?code=C192&pidm=630924&pamsVersionId=4360001

The privacy extension reports that it's blocking a tracker from srm.my.salesforce.com. But if you whitelist that domain, the sidebar is still absent. Even whitelisting srm--c.na60.visual.force.com is not good enough. You just have to whitelist **my.wgu.edu**. At first, I had forgotten I even installed this extension, so I was thinking the site was just broken in Firefox as I had already disabled Firefox's tracking protection for WGU. Perhaps a little on-page reminder would be nice instead of just having a blank sidebar because there's information here that students can't get anywhere else.

![wgu_course_sidebar](https://user-images.githubusercontent.com/42875253/45437776-60b40800-b66a-11e8-95ad-a31d15540df0.png)
Blocked content is everything on the right side. Course Instructor, Announcements, Course Tips, Course Search, Course Chatter.
![wgu_course_sidebar_blocked](https://user-images.githubusercontent.com/42875253/45438952-69f2a400-b66d-11e8-814d-5605ff181bbc.png)

**Comment by dharb** [comment]
Hey there @noerrorsfound, thanks for the thorough bug report! We really appreciate it. Breakage on sites that require logins to see is a thorny issue for us, so this is extremely helpful.

The reason this is broken stems from our use of the disconnect tracker list, which identifies salesforce.com and associated domains (eg force.com) as a tracker network: https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json#L4865
It's true that salesforce.com does a lot of tracking, however there are also legitimate cases like yours where third-party resources are fetched from salesforce.

I'd like to get this fixed for you as soon as possible. I'll go ahead and whitelist third-party requests to force.com/apex/CommonsSidebar. To be safe, let's also whitelist whatever requests to srm.my.salesforce.com are being blocked on that page. 

The trouble here is that I can't see what requests were actually made to that domain without a login. Can I ask you for a bit of help? Can you please:
- Whitelist my.gwu.edu
- Open dev tools (ctrl+shift+c or cmd+shift+c on mac)
- Click over to the network tab:
![image](https://user-images.githubusercontent.com/4481594/45441991-c1553c00-b68e-11e8-96a3-e669f59d5588.png)
- In the 'filter urls' input box, type 'force' to only show requests including the word 'force'
- Make sure that 'All' requests are shown by clicking 'All' to the right of the 'Filter URLs' box
- Reload the broken page (http://my.wgu.edu/courses/course/4360001/course-material)
- Upload a screenshot here of what appears in the network tab

Thanks again for your help, and apologies for breaking your course site!

**Comment by noerrorsfound** [comment]
![image](https://user-images.githubusercontent.com/42875253/45442787-d7a3cd80-b677-11e8-846d-710bdcd6be18.png)

**Comment by noerrorsfound** [comment]
![salesforce](https://user-images.githubusercontent.com/42875253/45442851-05891200-b678-11e8-9dbe-a7ba9bb5ba99.png)

**Comment by dharb** [comment]
Perfect, this is really helpful. Two more quick things (promise I won't ask any more of you) and then I'll have enough info to submit a patch to fix the site for you.
- Can you right click on the second request to srm.my.salesforce.com and copy URI and paste it here? This one: 
![image](https://user-images.githubusercontent.com/4481594/45443368-70dfdd80-b692-11e8-87c1-4f6b79a7febb.png)
- I see a lot of requests to salesforceliveagent.com, which is a live chat integration by salesforce. Does your course site have a live chat feature? If so, I'll be sure to unblock that as well.

**Comment by noerrorsfound** [comment]
https://srm.my.salesforce.com/apex/CommonsSidebar?code=C192&pamsVersionId=4360001&pidm=630924

There is a "WGU Chat" option that hovers along the bottom of all pages, so definitely whitelist that one! :)

**Comment by dharb** [comment]
Will do! Thanks again for all of the help, can't tell you how much we appreciate it. I'll patch this today and let you know when it is released.

**Comment by dharb** [comment]
Hey @noerrorsfound, this should be fixed now!
