### ISSUE TITLE
Ability to Use Dark Themed DDG Default Search Engine

### ISSUE THREAD

**Issue by mugdhosapiens** [duckduckgo/duckduckgo-privacy-extension#314]
DuckDuckGo Privacy Essentials is setting my default search engine which is fine. But I have brightness sensitivity, it's inconvenient for me to change the bright default theme every time i open Firefox and search on DDG. Please let us enjoy the ability to change the option so that i can enjoy dark theme at startup without any need for alteration every time.

**Comment by codeandbees** [comment]
Hey @mugdhosapiens have you tried a browser extension like [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/)?  It'll let you override default page styles to whichever theme you've installed, just did a quick test with the [global dark theme](https://userstyles.org/styles/31267/global-dark-style-changes-everything-to-dark?utm_campaign=stylish_stylepage) and it works on DDG! Hope that helps.

**Comment by jdorweiler** [comment]
You can change the default theme here https://duckduckgo.com/settings
