### ISSUE TITLE
extension modifies request origin schema from HTTP to HTTPS

### ISSUE THREAD

**Issue by vire** [duckduckgo/duckduckgo-privacy-extension#322]
Extension enforces in a implicit way the server to switch CORS schema from HTTP to HTTP in the `access-control-allow-origin` header resulting in behavior below.

```
The 'Access-Control-Allow-Origin' header has a value 'https://localhost:3000' that is not equal to the supplied origin. Origin 'http://localhost:3000' is therefore not allowed access.
```
chrome: chrome/69.0.3497.100
ext. version: 2018.9.28

In devtools network tab there are origin and referer displayed correctly with HTTP - see screenshot (RIGHT is extension **enabled**, LEFT extension **disabled**)
![screenshot from 2018-09-29 18-06-25](https://user-images.githubusercontent.com/4021908/46247922-a4e92b80-c412-11e8-84d9-79740311bd29.png)

**Comment by alfirin** [comment]
We have the same here.

We can't develop in localhost anymore with the extension activated.

**Comment by deltafsdevelopment** [comment]
We also have this issue - tried adding "localhost" to the whitelist but this had no effect.

**Comment by davidbeermann** [comment]
I also ran into this issue. I was able to resolve it by toggling the **Site Privacy Protection** checkbox in the extension window. This added `localhost` to the whitelist. What is a little confusing though is, that once you add a host to the whitelist, the whole extension window is disabled. In order to remove the host from the whitelist, you have to go through the extension management to get to the extension settings – at least in Chrome.

**Comment by azuroff** [comment]
Any ETA on a fix?  I just spent the last day trying to figure out why the header was being mysteriously changed.

**Comment by russellholt** [comment]
Fix is in progress. ETA is a couple of hours from now for FF.

**Comment by danielstaleiny** [comment]
fucking thank you for wasting half a day. 

Make some notes in the extension, or just make the localhost blacklisted in your tool.

**Comment by coolreader18** [comment]
`duckduckgo.com` is blocked on my network (I use `safe.duckduckgo.com`), and I'm pretty sure that makes *all* sites redirect to https. This means that not only localhost doesn't work, but any site on the internet that doesn't support https (a shrinking percentage of sites, but still. The most recent one that comes to mind is http://blogs.perl.org). If it were possible to add a setting to disable this redirection feature or to change the domain the extension fetches `smarter_encryption.js` from (I think that's the reason this is happening?) that would be greatly appreciated.
