### ISSUE TITLE
Nothing working in Firefox

### ISSUE THREAD

**Issue by colemickens** [duckduckgo/duckduckgo-privacy-extension#355]
I'm having enough of a hard time that I worry I'm doing something wrong, but nothing is working for me.

I reverted to stable Firefox (v64) and I'm seeing the following:

* in Options, I see "An extension, DuckDuckGo Privacy Essetnails, has set your default search engine." But, DDG is not in the list, is not the default, and is not used when typing in the omnibox

* When I go to duckduckgo.com, I do not have the option to Add DDG as a Search Engine. Yahoo, on the other hand, is presented as a search engine that I can add to Firefox

**Comment by colemickens** [comment]
Here's a screenshot of stable Firefox with a clean profile, failing to present DDG as a search engine option: 
![no-search-engine-option](https://user-images.githubusercontent.com/327028/49977476-54ef1080-fefb-11e8-999c-85177e060ba8.png)

**Comment by jdorweiler** [comment]
I haven't been able to repeat it. Are you still having this problem?

**Comment by colemickens** [comment]
Yes. On multiple machines. I've worked around this by hitting "Restore Default Search Engines", and then DDG Extension is properly setting the default engine (I normally manually remove them all). Not sure if the extension is failing to poke in DDG if it doesn't already exist in the search list?

Also, yes, DDG is still not an option to "Add Search Engine" to browser like Google/Yahoo have (I think done via like a <meta> tag or something).

**Comment by jdorweiler** [comment]
What OS are you using and do you have any other extensions that might be changing search engines?

**Comment by colemickens** [comment]
This has now happened on both Firefox and Windows. Extensions include: Tree Style Tabs, uBlock Origin, Gopass Bridge, nothing that would affect the search engine setting. IIRC when I filed this I even tried disabling the other extensions and restarting.

Flatly, I've never seen DDG Essentails work in a copy of Firefox that didn't already have DDG as an available, or the default, search engine.

This still works for you if you remove DDG from being a preset search engine?

**Comment by jdorweiler** [comment]
Ok, I can repeat it if I remove DDG from the default search engine list.

**Comment by jonathanKingston** [comment]
I can't see how to reproduce this anymore. Please comment back if it's still occurring.
