### ISSUE TITLE
Google Optimize asynchide delays page loads

### ISSUE THREAD

**Issue by fulldecent** [duckduckgo/duckduckgo-privacy-extension#360]
# Test case

Load any page with standard Google Analytics code (as recommended by Google) plus standard Google Optimize snippet (including "asynchronous hide" code as recommended by Google).

# Expected outcome

Page is loaded without Google tracker and also is equal or better in perceived page load time versus not using this extension.

# Actual outcome 

Page is loaded without Google tracker but page adds 4 seconds to first-pixel-to-paint time versus not using this extension.

---

# Specimen

One test specimen is at: https://pacificmedicalacls.com/

And here is the relevant code, almost minimal.

```html
<!doctype html>
<html>
  <head>
  <!-- Page hiding snippet (recommended)  -->
  <style>.async-hide { opacity: 0 !important} </style>
  <script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
})(window,document.documentElement,'async-hide','dataLayer',4000,
{'GTM-5QNVXJ7':true});</script>
  <!-- Global site tag -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-66686611-1" data-proofer-ignore></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-66686611-1', {
      'optimize_id': 'GTM-5QNVXJ7',
      'linker': {
        'domains': ['...'],
        'accept_incoming': true,
        'decorate_forms': true
      },
    });
  </script>
</head>
<body>
Hello world
</body>
</html>
```

Authoritative documentation: https://developers.google.com/optimize/#the_page-hiding_snippet_code

# Discussion

The way that the default code from Google works is as follows:

1. Delay loading the page for four seconds
2. Load the page-modifying experiment code
3. When the page-modifying experiment code finishes loading then abort \# 1 delay loading

The issue is that \# 1 is happening (page loading is delayed four seconds), then the \# 2 loading is blocked by extension. This results in the experience that the page is delayed for the full four seconds, rather than aborting the delay when the page-modifying experiment code is loaded from Google.

Four seconds is the recommended delay time by Google. And they reason they recommend a delay time at all is because the page-modifying experiment code may cause the entire page to be redrawn. Google does not expect this resource to be blocked, so they expect it to load quickly and the visitor will see the modified page first, rather than seeing the original page flash over to the modified page. The four second delay is a cop-out so that the page is not stuck forever in the unexpected case that the page-modifying experiment code fails to load.

# Recommendation

The DuckDuckGo Privacy Extension works by blocking resources. And a failed resource load is a situation that occurs rarely in nature. Because Google Optimize experiments are popular and have a bad user experience in this situation and because this extension is the responsible for this bad experience then therefore I recommend that this extension take responsibility to modify the "asynchide" functionality.

This is a dangerous precedent to set. (Many people could file issues asking us to fix broken stuff.) Also, we want to avoid modifying a page and causing /even worse/ behavior especially because the page designed wont expect us to be mucking around in this way.

Therefore I recommend we conservatively ONLY modify asynchide if we detect that the default Google-recommended implementation is used. OR if we can be reasonably assured that our modification will not cause undue harm.

Here is the most conservative modification that meets these requirements:

```txt
s*
<script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
})(window,document.documentElement,'async-hide','dataLayer',4000,
{'([a-zA-Z0-9-]+)':true});</script>
*
<script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
})(window,document.documentElement,'async-hide','dataLayer',1,
{'\1':true});</script>
*g
```

This reduces the delay from 4,000 milliseconds to one millisecond if and only if the exact recommended Google implementation is used.

If possible, this should be a user-configurable setting. I recommend if it can be implemented in this most conservative way then the setting would be enabled by default.

**Comment by jdorweiler** [comment]
Interesting, thanks for the detailed write up. It sounds like this is a case for adding a `googletagmanager.com/gtag` surrogate.  @dharb what do you think?

**Comment by kdzwinel** [comment]
Thank you @fulldecent, this bug report is 💯
Looks like we have to call `window['dataLayer'].hide.end()` via the surrogate.

**Comment by dharb** [comment]
This definitely sounds like a good case for adding a surrogate. This actually reminds me of the issue we've seen before on AMP pages where google adds an 8 second delay if their tracking request is blocked. I'll make note of this and investigate further.

**Comment by turbek** [comment]
Hi, 

I'm curious how this issue was solved. I see a js loading instead analytics.js and gtm.js which then calls the dataLayer.hide.end(), but I'm buffled that I didn't find traces where these come from. Is it loaded through the extension somehow or is it handled differently?

**Comment by jonathanKingston** [comment]
This looks like it was added (https://github.com/duckduckgo/tracker-surrogates/blob/main/surrogates/gtm.js) and I can't see broken pages that use this.

Closing out.
