### ISSUE TITLE
Firefox log spam: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by pipboy96** [duckduckgo/duckduckgo-privacy-extension#362]
## Description
Extension constantly writes errors to DevTools log.

## Steps to Reproduce
1. Install latest Firefox Nightly.
1. Install DuckDuckGo extension.
1. Open any website.

**Expected behavior:**
No error messages in DevTools.

**Actual behavior:**
DevTools is flooded by many copies of this error message:
`Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.`
Error messages always mention file "background.js", but line number is different for each message.

**Versions**
- Extension: 2018.6.28
- Browser: Firefox Nightly
- OS: Linux

**Comment by jdorweiler** [comment]
I'm not sure of a way to fix this. What happens is that as trackers are blocked the background notifies the popup to rerender some parts of the UI. This keeps the number of trackers and things blocked up to date with what is happening on the site. 
If the popup isn't open when the message is sent then it throws an `Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.`. It's not much of an error but is annoying to see in the console.

**Comment by pipboy96** [comment]
@jdorweiler The problem is that these messages are stored even if DevTools are not open, eating memory. A long browsing session could end up with thousands of log messages.

**Comment by jdorweiler** [comment]
@pipboy96 yeah good point. I looked into this some more and it turns out we can catch and ignore the error from `browser.runtime.sendMessage` but not from `chrome.runtime.sendMessage`. It seems like the fix is just to go around and switch all our use of `chrome.runtime.sendMessage`. I'll do some more testing and see if I can get a fix for this in the next week or two.

**Comment by Bruna17** [comment]
Unchecked lastError value: Error: Could not establish connection. Receiving end does not `exist.``

**Comment by jonathanKingston** [comment]
These issues have since been resolved, they still re-occur from time to time but our migration to the Mozilla shim auto catches these lastError messages and will handle this better.

Thanks for reporting!
