### ISSUE TITLE
Search bar doesn't save last search

### ISSUE THREAD

**Issue by mwkinney** [duckduckgo/duckduckgo-privacy-extension#379]
Current behavior: searching in the DDG PE search bar, going to the result and then reopening it to update the !bang results with an empty string.

Expected behavior: last search is saved for that browser session, and is the same string for all tabs. 

I understand this is likely some sort of privacy feature, but saving that last string in memory is well worth it. The major reason I use DDG is for bangs, which I sometimes revise the search string to slightly change the results or use another site for results.

**Comment by jonathanKingston** [comment]
So this looks like a duplicate of https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/91 I think the double bang proposal there makes more sense from a UI perspective (and the limitations of extensions).
