### ISSUE TITLE
local files should not be graded

### ISSUE THREAD

**Issue by ghost** [duckduckgo/duckduckgo-privacy-extension#381]
## Description
Local files in firefox (those with a `file://` URL) should not be graded.

## Steps to Reproduce
1. Create an html file
2. open the html file in firefox

**Expected behavior:**
The website should not be graded, similarly to what is done with `about:` URLs.

**Actual behavior:**
The website gets a C, because it has unknown privacy practices, and an unencrypted connection (obviously, because it is a local file)

**Comment by jash11** [comment]
Also, ping on #364
