### ISSUE TITLE
Is the Safari extension still available ?

### ISSUE THREAD

**Issue by antwake** [duckduckgo/duckduckgo-privacy-extension#387]
The introduction message says "DuckDuckGo Privacy Essentials browser extension for Firefox, Chrome, **Safari**" but the Readme doesn't link to a Safari version (only Chrome and Firefox).

And then the https://duckduckgo.com/app link only allow to "Set as Default Search Engine"

**Comment by brindy** [comment]
Hi @antwake,

You can find our Safari extension at https://apps.apple.com/us/app/duckduckgo-privacy-essentials/id1482920575?mt=12

We also released the source today, you can find it here:
https://github.com/duckduckgo/privacy-essentials-safari

Thanks!
