### ISSUE TITLE
Please make it possible to configure or disable the search keyword 'd'

### ISSUE THREAD

**Issue by cameronsstone** [duckduckgo/duckduckgo-privacy-extension#388]
## Summary
I have an existing dictionary search using firefox's 'd' search shortcut. Using this extension takes over the 'd' shortcut to search in duckduckgo which is useless to me as duckduckgo is already my default search engine. I would like to disable this awesomebar reconfiguration.

## Motivation
1. Don't change my things without asking.
2. Don't hardcode configuration.
3. Let me disable the addition of a search keyword.
4. [Optional] let me configure the search keyword.

## Additional context
Priority: I'm disabling this extension until you change it. I want "d search terms" to search the free dictionary for the search terms. If I want to search DDG I omit the keyword.

**Comment by Termuellinator** [comment]
i second this.
If you have installed this extension, you probably have DDG as your default search engine anyway, so this is kind of redundant

**Comment by dharb** [comment]
Thanks for the feedback, I totally understand how this could be annoying. I'll bring this up with the team.

**Comment by cameronsstone** [comment]
This fixes the problem for me. Feel free to resolve this issue. Thanks!
