### ISSUE TITLE
remove EFF sites from /shared/data/tracker_lists/entityMap.json

### ISSUE THREAD

**Issue by jawz101** [duckduckgo/duckduckgo-privacy-extension#392]
https://panopticlick.eff.org/about

    trackersimulator.org
    eviltracker.net
    do-not-tracker.org

These domains contain files used to simulate various tracking techniques.  By blocking these domains, the browser extension masks testing what tracking techniques might actually be in use elsewhere.

**Comment by jonathanKingston** [comment]
The fingerprint checking still appears to be loading in the test so this appears to be working as intended. Please reopen if this isn't the case.
