### ISSUE TITLE
jQuery 3.2.1 Vulnerability: Upgrade to jQuery 3.4.0 to Fix

### ISSUE THREAD

**Issue by PatOnTheBack** [duckduckgo/duckduckgo-privacy-extension#393]
## Description

Query 3.2.1 has a Prototype Pollution flaw. You can read about the [flaw on Snyk's website](https://snyk.io/test/npm/jquery/3.2.1).

## Steps to Reproduce
1. Use [Google Lighthouse](https://developers.google.com/web/tools/lighthouse/#devtools) to scan DDG Privacy Essentials Chrome Extension.
2. In the Lighthouse audit, it is reported that jQuery 3.2.1 is being used.

**Expected behavior:**

DDG Privacy Essentials should be using at least jQuery 3.4.0 to avoid this vulnerability.

**Actual behavior:**

DDG Privacy Essentials is using a vulnerable version of jQuery.

**Versions**

- Extension: 2019.5.29
- Browser: Chrome
- OS: All

**Comment by dharb** [comment]
Thanks for the heads up @PatOnTheBack. We'll get this upgraded in our next release.
