### ISSUE TITLE
Google Chrome crashes unexpectedly with Extensions Toolbar Menu enabled

### ISSUE THREAD

**Issue by omarowns** [duckduckgo/duckduckgo-privacy-extension#408]
## Description
When searching for anything on the toolbar after hitting <Enter> Google Chrome crashes.
Doesn't happen when visiting URLs.
Doesn't happen with search engines like Google or Amazon.

## Steps to Reproduce
1. Enable _Extensions Toolbar Menu_ in Chrome (chrome://flags)
2. Relaunch Chrome
3. Type anything into the toolbar
4. Press <Enter> to search

**Expected behavior:**
It should search whatever was typed and take you to the search results.

**Actual behavior:**
Google Chrome crashes.

**Versions**
- Extension: 2019.7.19
- Browser: Chrome
- OS: Mac

## Additional Information
I have enabled the Extensions Toolbar Menu in Chrome (chrome://flags)
![image](https://user-images.githubusercontent.com/1001797/63873090-8eca4f00-c984-11e9-875b-d01389b67a57.png)

**Comment by omarowns** [comment]
@jdorweiler I have two different profiles (or People) setup in Chrome, this bug happens in one of those profiles and with the other profile it doesn't happen.

**Comment by kdzwinel** [comment]
Hey! Quick update, the underlying Chrome bug got fixed last week:  https://bugs.chromium.org/p/chromium/issues/detail?id=985834 . Thanks for reporting!

**Comment by omarowns** [comment]
Yup, just tested this and the bug is gone, everything working as expected. Thanks for letting us know @kdzwinel !
