### ISSUE TITLE
Duckduckgo privacy essential extension blocking twitter embedded code

### ISSUE THREAD

**Issue by StewAlexander-com** [duckduckgo/duckduckgo-privacy-extension#414]
With your DuckDuckGo Privacy Essentials Extension Enabled on Chrome twitter embedded code does not render on a website:

With the DuckDuckGo extension enabled:
![image](https://user-images.githubusercontent.com/48565067/64796358-8e69b080-d54d-11e9-993c-1d551559027a.png)

With your DuckDuckGo extension disabled:
![image](https://user-images.githubusercontent.com/48565067/64796481-c113a900-d54d-11e9-809a-a21b87b8e30c.png)

![image](https://user-images.githubusercontent.com/48565067/64796521-d12b8880-d54d-11e9-8dce-c44743bc89d6.png)

If you would like the embedded code I can provide it.

Here is where one can get the embedded code: https://publish.twitter.com/#

**Comment by edsu** [comment]
I'm curious why Twitter has been special cased. It appears that I can still view Instagram embeds, which use roughly the same technique? Is the plan to apply this across the board to other embeds from social media platforms, at least in principle?
