### ISSUE TITLE
Privacy Grade Icon

### ISSUE THREAD

**Issue by PeterKW** [duckduckgo/duckduckgo-privacy-extension#432]
The chrome icon seems to have switched to the DuckDuckGo icon rather than the privacy Grade of the current page which is a shame.

**Comment by swetankraj** [comment]
@PeterKW could you please elaborate on the issue?

**Comment by jdorweiler** [comment]
This was a bug in Chrome. Should be fixed now https://bugs.chromium.org/p/chromium/issues/detail?id=1049214
