### ISSUE TITLE
extension breaks radio garden

### ISSUE THREAD

**Issue by puckey** [duckduckgo/duckduckgo-privacy-extension#434]
This extension breaks the following website: http://radio.garden

Due to Chrome no longer supporting mixed content (http/https) and because 85% of internet radio streams are still on http, we were forced to redirect https visitors down to http.

This extension then upgrades them back to https - causing an endless loop.

Using the extension, I am also unable to report the issue to you.

**Comment by puckey** [comment]
@MariagraziaAlastra do you happen to know if there is another channel I should be using for an issue like this?

**Comment by dharb** [comment]
@puckey sorry about the HTTPS upgrade issue, I'll get this fixed for you.

**Comment by puckey** [comment]
Awesome - thanks.

**Comment by dharb** [comment]
This should be fixed now 👍
