### ISSUE TITLE
Not available for macOS less than 10.15

### ISSUE THREAD

**Issue by adunning** [duckduckgo/duckduckgo-privacy-extension#438]
The new app with the content blocker is fabulous. When I attempt to download the DuckDuckGo extension on the Mac App Store on macOS 10.13, however, it gives me an error stating that it is only available for version 10.15. Presumably this is not a necessary restriction, given that Safari 13.1 is still being updated for 10.13.

**Comment by brindy** [comment]
Hi @adunning, thanks for the feedback.

Unfortunately we use a UI component that is only available in macOS 10.15 or newer. 

If you're interested in the code we published that today and you can find it here: https://github.com/duckduckgo/privacy-essentials-safari

Thanks!
