### ISSUE TITLE
Resources from squareup.com domains are being blocked

### ISSUE THREAD

**Issue by brettstimmerman** [duckduckgo/duckduckgo-privacy-extension#457]
## Resources from squareup.com domains are being blocked
Since 632026df, cross-domain requests for squareup.com resources are intermittently being blocked. This prevents at least Square's online payments JavaScript from loading on merchant sites, making payment impossible, and potentially causing other issues.

## Steps to Reproduce
1. As one example, visit a site using Square online payments. Say, https://squareup.com/shop/hardware/us/en
2. Add an item to the cart, and proceed to the Checkout step
4. The Checkout page makes a request to https://js.squareup.com/v2/paymentform to load JavaScript necessary to initiate online payments with Square.

**Expected behavior:**
https://js.squareup.com/v2/paymentform is not blocked.

**Actual behavior:**
https://js.squareup.com/v2/paymentform is blocked.

**Versions**
- Extension: 2020.5.28
- Browser: Chrome
- OS: Mac

## Additional Information
There are small number of subdomains and resources on them Square uses in the process: at least js.squareup.com and pci-connect.squareup.com.

**Comment by jdorweiler** [comment]
Thanks @brettstimmerman, this should be fixed now.

**Comment by brettstimmerman** [comment]
Thanks for a quick fix!  I've tested briefly myself and have gotten another confirmation that it's no longer being blocked.

**Comment by jdorweiler** [comment]
Great, thanks for testing.
