### ISSUE TITLE
Edge Chromium's "Translate to.." blocked as tracker

### ISSUE THREAD

**Issue by th3m** [duckduckgo/duckduckgo-privacy-extension#464]
The Edge Chromium "Translate to..." is broken cause the extension is blocking as tracker the domain

api.cognitive.microsofttranslator.com

When i try to whitelist the domain within the extension options, it accepts it and stores it as a value but it still blocks it as a tracker. (This tracker obviously appears and gets blocked only when i try to use the browser's built-in auto translate feature)

Making the only way to be able to use this translate feature, is by having to turn off the Site Privacy Protection toggle of the extension but now being open to trackers on the site i am visiting and trying to translate.

I believe there should be an accepted behavior of allowing this feature, or be able to control it somehow without the need of toggling off the extension.

**Comment by dharb** [comment]
Thanks for letting us know, and sorry about that. We try to do tracker detection in as automated a way as possible, unfortunately this has the side effect of sometimes blocking things that break the web experience. I'll get a fix out for this early next week.

**Comment by th3m** [comment]
Thank you, it is fixed on 2020-7-9 release.
