### ISSUE TITLE
Extension causes Firefox to ignore size in window.open()

### ISSUE THREAD

**Issue by hkockerbeck** [duckduckgo/duckduckgo-privacy-extension#498]
## Description
When I open a new window with the JavaScript function `window.open()`, I can set the width and height the new window should have. The extension seems to cause Firefox to ignore those parameters.

## Steps to Reproduce
1. Deactivate the extension
2. Click on a link like `<a href="javascript:window.open('https://www.duckduckgo.com', 'name_of_window', 'height=500,width=500')">Test link</a>`. The new window should be of the specified size.
3. Activate the extension
4. Click on the link again. The new window probably is not of the specified size, but uses all available width and height on the display (but isn't maximized, either). 

**Expected behavior:**
I expect Firefox with the extension enabled to honor the specified width and height of new windows.

**Actual behavior:**
The extension seems to filter out the `width` and `height` parameters at least. I didn't test other window features that `window.open()` supports in the third argument.

**Versions**
- Extension: 2020.10.13
- Browser: Firefox
- OS: Linux

## Additional Information
The issue was probably introduced in the latest version of the extension, or at least not too long ago. I've been using the extension for some time now, and the problem only appeared quite recently.

**Comment by Charlie-belmer** [comment]
I tested this in the latest release and it appears resolved.
