### ISSUE TITLE
Site Protection Blocks Google Recaptcha

### ISSUE THREAD

**Issue by Chidhambararajan** [duckduckgo/duckduckgo-privacy-extension#500]
I am using Brave 86.1.15.75 in Ubuntu 20.04 Lts 

Whenever I try to login into coursera.org , I am faced with "Please upgrade to a supported browser to get a reCAPTCHA challenge." . I tried turning of brave shields , yet didn't work . Turning off site protection in duckduckgo's extension did the trick

I have the same extension installed in firefox too , didn't face any issues there..

Is it a bug??

**Comment by Charlie-belmer** [comment]
Thanks for reporting!

This appears to be a problem with our recent fingerprint protections, where the UserAgent is randomized when sent to third parties. It only seems to happen on Brave, and I am not sure why that is.

In any case, we will be releasing a fix to the safe list code shortly that will allow us to safe list reCaptcha for user agent spoofing, which should solve this issue.

**Comment by Charlie-belmer** [comment]
I tested this in the latest release and it appears resolved.
