### ISSUE TITLE
Firefox XML view: JavaScript and other output

### ISSUE THREAD

**Issue by ActionScripted** [duckduckgo/duckduckgo-privacy-extension#503]
## Description

Firefox XML view broken; contains JavaScript and other extraneous output.

## Steps to Reproduce

1. Open Firefox
2. Add/enable this extension
3. View an XML feed or file

**Expected behavior:**

Standard XML browser.

**Actual behavior:**

Mangled output with JavaScript.

**Versions**

- Extension: 2020.10.13
- Browsers: Firefox 82.0 (64-bit) and Firefox 83.0b2 (64-bit)
- OS: macOS

## Additional Information

Screenshot attached showing expected (left; plugin disabled) versus what happens (right; plugin enabled). Have tested this with all other plugins disabled.

![ddg-privacy-bug](https://user-images.githubusercontent.com/708612/96741556-ec430b80-138f-11eb-91d6-455435b8603b.png)

**Comment by ActionScripted** [comment]
This is an issue even when the URL/file ends with `*.xml` e.g., https://feedforall.com/sample.xml

**Comment by Charlie-belmer** [comment]
Thanks for reporting!

This looks like it's a result of the anti-fingerprinting features we released recently. I just made a PR which should fix this by filtering out xml and json content types. 

If you have some sites I can test with, I would appreciate it, otherwise this should go out in a future release.

**Comment by ActionScripted** [comment]
I don't have any specific sites but I've been noticing it on anything with an RSS/XML feed. Noticed it first when setting up our new company site/blog and testing Gatbsy's RSS generation (via https://merit-network.github.io/rss.xml).

Thanks so much!

**Comment by vpArth** [comment]
What is date for this merge(fix xml/json data) to be released?

**Comment by vpArth** [comment]
Also, is there any chance to have a gui switch to turn off that antifingerprint injection feature?

**Comment by Charlie-belmer** [comment]
Unfortunately there isn't a disable toggle at this time for that feature. 

Though I don't have an exact date yet, this fix will be included in the next feature release, which is likely to be in the next couple of weeks.

I know it's not an ideal solution, but until then, disabling the site protections when you want to use the XML view should work.

Thanks!

**Comment by vpArth** [comment]
Main issue for me is not just direct xml view. It injects into ajax loaded xml-data on some services I use and leaks into gui =)

![][1]

[1]: https://imgur.com/fKGStLE.png

**Comment by Charlie-belmer** [comment]
We're planning to release this fix next week (assuming the holiday doesn't bump the release back). I'll comment here once it's fully released.

**Comment by ActionScripted** [comment]
Thanks @Charlie-belmer !

**Comment by jonathanKingston** [comment]
This has been fixed for quite some time. Closing out.
