### ISSUE TITLE
Privacy Extension is blocking remote calls to google services

### ISSUE THREAD

**Issue by jiblits** [duckduckgo/duckduckgo-privacy-extension#506]
## Description
With the DDG Security Essentials plugin enabled, remote calls to google services (such as firebase) are blocked by the plugin. I'd noticed this while trying to log into my brewing software at Brewfather.app

If I was already authenticated, the application would think I'm offline. If I wasn't logged in, the application would say my password is wrong.

## Steps to Reproduce
With a logged in account:
1. With the plugin disabled, sign up for an account at https://web.brewfather.app
2. Re-enable the security essentials plugin
3. Reload the page.

Logging in:
1. Ensure that the security essentials plugin is enabled
2. Remove all site data for brewfather.app from Firefox
3. Go to https://web.brewfather.app
4. Type in your username and password

**Expected behavior:**
With a logged in account, the application shows me my recipes.
When attempting to login, the login succeeds and I am brought to my recipes page.

**Actual behavior:**
With a logged in account, the application states that I am offline.
When attempting to log in, the application states that my username/password is incorrect.

**Versions**

- Extension: 2020-10-13 and later
- Browser: Firefox
- OS: MacOS

## Additional Information

**Not online when previously logged in**
<img width="1552" alt="Screen Shot 2020-10-22 at 07 32 48" src="https://user-images.githubusercontent.com/33376830/96870041-50240d80-143e-11eb-81c1-b26f0d6c61de.png">

**Blocked requests in Firefox developer console**
<img width="1552" alt="Screen Shot 2020-10-22 at 08 02 24" src="https://user-images.githubusercontent.com/33376830/96870221-924d4f00-143e-11eb-9fa1-7bc98c2af9f2.png">

**Comment by Charlie-belmer** [comment]
Hi @jiblits, thanks for reporting!

I'm sorry you are facing this problem. It looks like it's related to the new fingerprinting defense features. We have a release which should fix this issue currently going through extension approvals. It should update within a few days.

Thanks!

**Comment by Charlie-belmer** [comment]
The latest release came out a couple of hours ago, and this now appears resolved. Please let me know if you continue to experience issues.
