### ISSUE TITLE
video fails to load wcoanimedub.tv

### ISSUE THREAD

**Issue by Morku** [duckduckgo/duckduckgo-privacy-extension#507]
## Description

On this page, when you try to start the video, it fails to load when the Extension is active.

## Steps to Reproduce

1. Browse: https://www.wcoanimedub.tv/dragon-ball-super-episode-83-english-dubbed
2. press play button
3. "Video is unavailable or not supported" error

**Expected behavior:**
<details><summary>Screenshot-1:</summary>

![2](https://user-images.githubusercontent.com/6276915/97176637-87275580-1795-11eb-9f28-2782b1e4fea0.png)

</details><br/>

**Actual behavior:**
<details><summary>Screenshot-2:</summary>

![1](https://user-images.githubusercontent.com/6276915/97176660-8e4e6380-1795-11eb-86ff-e92aaa77eba9.png)

</details><br/>

**Versions**

- Extension: 2020-10-21
- Browser: Firefox
- OS: Window 10

## Additional Information

issue  is repeatable
Screenshots are in Actual and Expected behavior.

**Comment by JeppeX** [comment]
Failed to reproduce in linux environment (DDG v. 2021.1.8 in firefox)

**Comment by Morku** [comment]
🤷‍♀️ it's now 3 1/2 month when I reported and I uninstalled the extension, because no one is taking github reports serious here.

So I don't know if the page changed or if an DDG update solved it. I don't care anymore.

**Comment by jonathanKingston** [comment]
Closing as wasn't able to reproduce. Websites often change as does our blocklist. Thanks for the reporting!
