### ISSUE TITLE
Privacy Essentials crashes Brave on Mac when searching in private tabs

### ISSUE THREAD

**Issue by posita** [duckduckgo/duckduckgo-privacy-extension#510]
## Description
With Privacy Essentials enabled for private tabs, searches in private tabs crash the latest versions of Brave on OS X.

## Steps to Reproduce

1. Fire up Brave on OS X.
2. Install [DuckDuckGo's Privacy Essentials](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg).
3. Allow the extension to run in private tabs.
4. Open a new private window/tab.
5. Type some search terms (e.g., `test search on private tab`) into the address bar and hit return.

**Expected behavior:**
The page to load the search results for the typed search.

**Actual behavior:**
The Browser crashes (creating a new crash report in `brave://crashes/`). Uninstalling Privacy Essentials or disabling it in private tabs restores the expected behavior.

**Versions**

- Extension: 2020.10.21
- Browser(s):
  - Version 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64) _[latest at the time of this writing]_
  - Version 1.15.75 Chromium: 86.0.4240.99 (Official Build) (x86_64)
- OS: OS X (Mac)

**Comment by dharb** [comment]
Thanks for the report, we've been running into issues with searching from Brave private tabs for a few months now. I suspect what you're running into is related to this issue I opened an issue on their repo: https://github.com/brave/brave-browser/issues/10549, although I wasn't seeing the browser actually crash. Mind reporting this over there? Crashing behavior may motivate them to address it more quickly.

**Comment by posita** [comment]
Ah! I missed that one. Done. And thanks for the pointer!

**Comment by dharb** [comment]
Thank you for the report, and for filing the crash reports with them! Hopefully they address this soon.
