### ISSUE TITLE
DDG Privacy Essentials breaks WeVideo screen recording

### ISSUE THREAD

**Issue by mtconleyuk** [duckduckgo/duckduckgo-privacy-extension#514]
## Description
We cannot enable file access for WeVideo under Chrome for macOS or on Chromebooks. Works on Windows.

## Steps to Reproduce
1. Install DDG Privacy Essentials via GSuite in an OU of which you are a member. Or install it manually, if you don't use GSuite.
2. Reset all site settings in Chrome Settings.
3. Go to wevideo.com and login. Create a new account using Google if necessary.
4. Once logged into WeVideo, click on the Dashboard tab at the top of the page.
5. Click the Recording item.
6. In the Record From dialog, choose Webcam. Click Next.

**Expected behavior:**
Chrome should ask to allow WeVideo access to camera, microphone, and filesystem.

**Actual behavior:**
Chrome asks for access to camera and microphone, but not filesystem, and WeVideo puts up an error alert that reads 'Allow Access. WeVideo needs permission to record. Follow these instructions and try again.' Clicking Got It and trying again makes no difference.

This behaviour continues until DDG Privacy Essentials is disabled or removed. After that, everything works as expected.

Note that this happens even if the site is marked as unprotected in DDG Privacy Essentials and reloaded.

**Versions**
- Extension: 2020.10.21
- Browser: Chrome, latest version.
- OS: macOS or ChromeOS.

## Additional Information
This issue is 100% reproducible on any device running macOS or ChromeOS.

**Comment by dharb** [comment]
Thank you for the detailed report, I was just able to repro the issue on my machine. Not totally clear what's causing it yet, but I suspect it's related to the fingerprinting protections we recently shipped. I'll make sure this gets to the right person and let you know when we've shipped a fix.

**Comment by dharb** [comment]
Just wanted to let you know that we've identified a fix and will be shipping it in an update next week. Apologies again for causing the breakage.

**Comment by mtconleyuk** [comment]
Cheers! Many thanks for the quick fix.
