### ISSUE TITLE
Chronometer is broken

### ISSUE THREAD

**Issue by harshhhdev** [duckduckgo/duckduckgo-privacy-extension#517]
## Description
Chronometer has a flicker on hover (for desktop, works fine on mobile_

## Steps to Reproduce

1. Search "chronometer"
2. Press "start"
3. Hover over while it is running. 

**Expected behavior:**

I expect it to stand still and not flicker crazily. 

**Actual behavior:**

Everytime I hover over it, it flickers with a very weird effect which makes it hard to actually turn the thing off,

**Versions**

- Extension: 20.10.21
- Browser: Brave (based off of Chromium)
- OS: Linux (Pop!_OS 20.10)

## Additional Information

I am using a custom there on my Gnome desktop (the theme is white-sur-dark), this might be a cause for this. 
On mobiles this does not happen.

**Comment by dharb** [comment]
Hm, I can't seem to repro this issue. Tested with Ubuntu 19.10 and Windows 10 on Brave and Firefox. Couple questions to help figure this out:
- Do you have any other extensions installed that might be interacting with the DOM?
- Can you try in Chromium and/or Firefox? That should help us learn if it's specific to Brave
- Can you try in Brave with a standard Gnome theme? I wouldn't think that this would affect it, but 🤷 

Thanks!

**Comment by harshhhdev** [comment]
Hello, @dharb , thanks for getting back to me.

I tried to disable all extensions and still didn't work.
I have tried it on Chromnium and Firefox. It doesn't glitch out on either of them.
I did switch back to the default theme but it still did the silly glitch effect.

It worked on all other browsers I had installed. Just not this one. I'll try to upload a private video to YouTube and send the link to better demonstrate what I mean.

**Comment by harshhhdev** [comment]
Hey, I made a video to demostrate. Here's a link

https://www.youtube.com/watch?v=OYoV-PMid5k&feature=youtu.be

**Comment by dharb** [comment]
Thanks for sharing the video, super helpful. I still can't seem to repro the issue, my best bet is it's something to do with the fonts you have installed on your OS.

Do you mind filing this over in https://github.com/duckduckgo/zeroclickinfo-goodies instead since it doesn't seem to be related to the browser extension?

**Comment by SteveSajeev** [comment]
Is this thread solved. Even though it is closed. I would like to know if this is fixed.

**Comment by harshhhdev** [comment]
Update, this issue does not persist anymore, at least for my device. :+1:
