### ISSUE TITLE
Prevent display of post-install page when first logging into Chrome

### ISSUE THREAD

**Issue by mtconleyuk** [duckduckgo/duckduckgo-privacy-extension#519]
## Summary
When students log into our Chromebooks, DDG Privacy Extension loads and displays the post-install page (https://duckduckgo.com/app?post=1&atb=v250-2) as Chrome launches initially, which is a bit annoying. It would be nice if there were a way to disable this page, especially if we could do it from GSuite. There's no real need to remind students every time they log into their devices that DDG is there.

## Motivation
- Almost no other extensions that we load display a page (Ghostery does, but we don't force that installation; we do force uBlock, which is silent).
- Because Chromebooks aren't particularly speedy, this just adds more time to the login process, which strains the patience of students and teachers.

**Comment by dharb** [comment]
Thanks for the report! This sounds annoying, and like something that we shouldn't be doing. I don't have a Chromebook but I do have a ChromeOS VM that I can use to try to repro the issue and figure out what's going on. My initial thought is that Chrome must be deleting all localstorage (including extension localstorage) upon logout, which is making our extension forget that its already shown the post install page (see https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/develop/shared/js/background/atb.es6.js#L210).

Can I ask a couple quick questions to help debug?
- Is this happening on every single Chrome launch? Or is it just on the first Chrome launch after logging in?
- Does Chrome automatically open like this on login when our extension is not installed? Or does it seem like it's our extension that's making it open?
- Is there anything special about the way the DDG extension is being installed on your students' Chromebooks? Or anything special about Chrome's configuration?

**Comment by mtconleyuk** [comment]
- It happens on the first launch of Chrome following a login. So it's likely that, yes, the local storage is being cleared between logins.
- When you say 'open like this' I'm not quite sure what you mean. On login, Chrome automatically launches; that's just the way it is on a Chromebook. Or, at least, that's the way we have it set (I'm not sure whether this is a GSuite setting or just the default behaviour of the OS; I could check if that helps).
- The DDG extension is being force-installed. I don't believe there are any other special considerations (we do have a number of default settings for student accounts, but other than perhaps the local storage deletion mentioned above, I don't think any of them would affect extension loading in this case).

**Comment by dharb** [comment]
Gotcha, yeah it sounds like it's due to localstorage being cleared on logout. I'll take this internally and see if we can't find a fix. Will update here when I have more info.

**Comment by dharb** [comment]
@mtconleyuk just wanted to follow up with you on this. We investigated and have an idea as to how we can fix this issue. Before we proceed with the fix, I have one more question - after login when Chrome starts up, do any other tabs open aside from the DDG post install page?

**Comment by mtconleyuk** [comment]
Yes, we typically open up a school homepage tab first. Sometime after that, the DDG tab opens up.

**Comment by dharb** [comment]
Thanks for the info, I'll get a fix out in our next release (just missed today's release, which should be rolling out now).

**Comment by jonathanKingston** [comment]
This was fixed in https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/643 with instructions on how to configure the extension to disable this page.

Thank you for raising the suggestion, please let us know if this meets your needs!
