### ISSUE TITLE
Fingerprint protection sets properties on wrong object, making matters worse

### ISSUE THREAD

**Issue by palant** [duckduckgo/duckduckgo-privacy-extension#526]
## Description
Fingerprint protection functionality will overwrite various properties such as `screen.availHeight`. This is supposed to make fingerprinting harder. However, this change is easily reverted by websites. So rather than using one data point for fingerprinting, the website has two: the original value of `screen.availHeight` and the manipulated one.

## Steps to Reproduce
1. With DuckDuckGo Privacy Essentials enabled, type the following into JavaScript Console: `console.log(screen.availHeight, screen.height)`
2. Note the values being identical (assuming that you have a horizontal taskbar, this is fingerprint protection at work).
3. Now type in `delete screen.availHeight` and repeat step 1.

**Expected behavior:**
The result doesn’t change

**Actual behavior:**
The original value of `screen.availHeight` is displayed which is different from `screen.height`

**Versions**
Any, the problematic code is located here:

https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/52ed42042f6e466bc26b3fdd91a8de3c89451938/shared/data/fingerprint-protection.js#L26

## Additional Information
By default, the property `availHeight` is defined on `Screen.prototype`, that’s where it needs to be overwritten – this won’t let websites revert the change. Also, it should be the same property descriptor as the default implementation, meaning:

    { get: () => screen.width, enumerable: true, configurable: true }

It’s desirable to make the manipulation itself hard to detect, because it’s also a data point which can be used for fingerprinting.

**Comment by dharb** [comment]
Thanks so much for the detailed report @palant. I'll take this internally and see if we can get a patch out next release.

Unrelated, but I want to take this opportunity to tell you how much I appreciate the work you did to expose Jumpshot last year.

**Comment by palant** [comment]
I wrote an extended version of this in a blog post, also covering additional issues: https://palant.info/2020/12/10/how-anti-fingerprinting-extensions-tend-to-make-fingerprinting-easier/. AFAICT from the source code, DuckDuckGo Privacy Essentials is affected by all four issues described there.

**Comment by palant** [comment]
And while I have you here @dharb, I also have some minor security issues. What’s the best way to report them? I don’t really want to create a public GitHub issue…

**Comment by Charlie-belmer** [comment]
Thanks @palant, I'll be updating our protection with your recommendations - love the article by the way, super helpful.

For security issues, you can drop a note to me at cbelmer(at duckduckgo) and I'll take a look. The official way is via HackerOne, but I'm happy to just take a look.

**Comment by Charlie-belmer** [comment]
Made a quick PR with some of the fixes here: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/527. I'd definitely appreciate any thoughts you have around it.

Looking through your article, we're specifically not using content scripts to avoid the timing & state issues you mentioned, but the dynamic iFrame is a new one I hadn't considered, and requires more research.

**Comment by palant** [comment]
> we're specifically not using content scripts to avoid the timing & state issues you mentioned

Does it work? This was the part I was unsure about, but from what I understand loading a content script from `webNavigation.onCommitted` doesn’t give you any guarantees that this content script will run before website scripts can. In particular, an inline script in the page head should be able to access the values before the content script gets a chance to run.

**Comment by Charlie-belmer** [comment]
hmm, it's true that inline head scripts can access the values before the extension changes them, but JS files loaded in head (via <script src=..>) can't (at least, I wasn't able to get them to). I haven't seen any fingerprinters that use inline head fingerprinting scripts in the wild though. 

Content scripts seem like they would help with this issue and the dynamic iFrame issue. My main concern is still the delayed disable / async communication to the extension (which is why I chose onCommitted in the first place). We tend to prioritize minimal breakage over maximum protection, and I worry that if anything in the script breaks in odd ways for a site, there isn't a way to truly disable the functionality.

Thanks again for creating this issue and helping us out!

**Comment by palant** [comment]
> I haven't seen any fingerprinters that use inline head fingerprinting scripts in the wild though.

Note that this doesn’t have to happen on the top level. A third-party fingerprinting script could always create a frame and pull this timing trick there.

**Comment by Charlie-belmer** [comment]
Several of these fixes went in with #527, so I am going to close this issue. The PR doesn't fix everything raised here, but we have opened some longer term projects internally to review some of the harder to correct ones (like timing). Thanks again for all the help here.
