### ISSUE TITLE
Marks (file://)-URLs as unsecure

### ISSUE THREAD

**Issue by Bimi124** [duckduckgo/duckduckgo-privacy-extension#539]
## Description

Looks lile some `file://` URLS have "Unknown Privacy Practices" or "Unsecure Connection"

## Steps to Reproduce

1. open file on local machine

**Expected behavior:**

ignores category "Unknown Privacy Practices" ans "Unsecure Connection"

**Actual behavior:**

detects "Unknown Privacy Practices" or "Unsecure Connection"

**Versions**

- Extension: 2021-1-8
- Browser:  Firefox
- OS: Windows

**Comment by jonathanKingston** [comment]
Both of these things are true:

1. `file://` could map to a networked resource served over an insecure connection.
2. `file://` could be a saved web page which could be used for local tracking.

In some ways `file://` could be used to phish or attack users more than other protocols, for example Browsers will treat everything in `~/Downloads` as same origin so the html file would be able to read anything within it. `file://` also is considered as as a secure context, which means it gets access to things HTTP wouldn't.

Perhaps we could explain this more thoroughly. I'm interested in your thoughts @Charlie-belmer

**Comment by Bimi124** [comment]
I know what file:// URLs are and I think secure connention isn't required because ist's local. Okay, some Websites could use this technique but at least Firefox users are asked if they want to do so.

**Comment by jonathanKingston** [comment]
Closing as I think this is the correct behaviour that we use in our other clients.
