### ISSUE TITLE
DDG extension breaks "press and hold esc to escape fullscreen" in stadia and geforce now

### ISSUE THREAD

**Issue by superusercode** [duckduckgo/duckduckgo-privacy-extension#547]
## Steps to Reproduce

1. log into GFN/stadia. Both services have free tiers and games to facilitate testing.
2. Open game
3. When the game "launches" and goes into fullscreen it will show that you can press to escape rather than (the usual) hold to escape. This is problematic since the escape key is essential to navigating game menus.

**Expected behavior:**
Hold to escape is available so I can navigate menus in games.

**Actual behavior:**
Pressing escape to leave menus unfullscreens the game while also passing no input, making the site unusable and forcing me to disable DDGPE. 
**Versions**

- Extension: 2021.08
- Browser: Microsoft Edge | 90.0.796.0 (Official build) canary (64-bit)
- OS: Windows 10 OS Version 2009 (Build 19042.804)

## Additional Information
Consistently breaks on stadia and geforce now, likely impacts other sites that use "press and hold <kbd>Esc</kbd> to exit to fullscreen"

DDGPE on:
![image](https://user-images.githubusercontent.com/60588434/108018583-2c389900-6fe6-11eb-8816-c608245a3414.png)

DDGPE off: 
![image](https://user-images.githubusercontent.com/60588434/108018625-45414a00-6fe6-11eb-9233-1867d264590c.png)

**Comment by dharb** [comment]
@superusercode thank you so much for the thorough bug report. I've repro'd the issue and identified a fix, we'll get a patch out shortly.
