### ISSUE TITLE
Resources from hubspot.com domains are being blocked

### ISSUE THREAD

**Issue by Jinukurian7** [duckduckgo/duckduckgo-privacy-extension#554]
I'm loading a meeting widget in my website with hubspot and seems duckduckgo privacy extension blocking it. 

## Description

**HTML markup** 
`<div class="meetings-iframe-container" data-src="https://app.hubspot.com/meetings/*****/embed=true"></div>`

**script to inject iframe**
`<script type="text/javascript" src="https://static.hsappstatic.net/MeetingsEmbed/ex/MeetingsEmbedCode.js"></script>`

<img width="383" alt="Screenshot 2021-02-23 at 10 42 43 AM" src="https://user-images.githubusercontent.com/12541253/108804792-406f2e00-75c4-11eb-96a7-fdbe7cddf281.png">

**Comment by sammacbeth** [comment]
Thanks for reporting this. We've just updated our blocklist to add an exception for this. Please let us know if it fixes the issue for you.

**Comment by Jinukurian7** [comment]
Hi Sam,

Thank you looking into this. I think duckduckgo still blocks hubspot.
Please check my screenshot


[image: image.png]

<https://about.me/jinu?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
Jinu Kurian
+91 88912 80830 <+918891280830>
about.me/jinu
<https://about.me/jinu?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>

**Comment by sammacbeth** [comment]
We've made another update that fixed the issue in my testing. If you're still having problems please post a link where we can reproduce the issue and find which blocked script is the problem.

**Comment by Jinukurian7** [comment]
@sammacbeth Thanks a lot !! It's working now.
