### ISSUE TITLE
Not able to access the shop page on fender.com

### ISSUE THREAD

**Issue by royalblue** [duckduckgo/duckduckgo-privacy-extension#556]
## Description
The shop page on the website is not loading and the code report an overflow

## Steps to Reproduce

1. go to fender.com (in firefox with only the DDG extension enabled)
2. click on the top menu -->  on parts --> then on the middle menu on strap locks & buttons
3. nothing happen and the store does not open
4. now disable the extension 
5. reload the page fender.com and proceed again from point 2
6. the store is accessible

**Expected behavior:**
the store should open normally

**Actual behavior:**
the store does not load

**Versions**

- Extension: 2021.1.8
- Browser:  firefox ver 86.0 (32-bit
- OS: windows 10 - Education N

**Comment by jonathanKingston** [comment]
Reproduced; there are several trackers blocked on the site but I suspect the main issue here is `https://cdn.segment.com/analytics.js/v1/{{integration-id}}/analytics.min.js` which manages the connections with them all.

I also see https://eu-library.klarnaservices.com/lib.js blocked which may be more detrimental to actually paying later on.

When the link is clicked and the protection is disabled I see the following:
![image](https://user-images.githubusercontent.com/338988/109483235-e87a7080-7a76-11eb-8c52-09f19f3dbd3a.png)

**Comment by sammacbeth** [comment]
This should have been fixed now by a blocklist update. Thanks for reporting!
