### ISSUE TITLE
Locking up on Konva (Canvas) Applications

### ISSUE THREAD

**Issue by abrahamfathman** [duckduckgo/duckduckgo-privacy-extension#560]
## Description

Chrome browser tab becomes unresponsive. A dialog saying 'Page Unresponsive' is shown with the choice to 'Exit Page' or 'Wait'
## Steps to Reproduce
1. Go to a site that is using Konva - like their demo here: https://konvajs.org/docs/sandbox/Free_Drawing.html
2. Try to scroll up and down on the web page

**Expected behavior:**
The web page will be responsive and you can see the HTML Canvas elements functioning.

**Actual behavior:**
Within 10 seconds, the browser page becomes unresponsive.

**Versions**
- Extension: 2021.3.2
- Browser: Chrome: 88.0.4324.192 (Official Build) (x86_64)
- OS: Mac

## Additional Information
This is repeatable every time.
This started with version 2021.3.2.

**Comment by jonathanKingston** [comment]
Thanks for the report!

`this.hitCanvas.context.getImageData(Math.round(pos.x * ratio), Math.round(pos.y * ratio), 1, 1).data`

I'm seeing this as the source of the troubles, I think it's because the subset of the canvas data we are modifying.
