### ISSUE TITLE
Support chrome.storage.managed to turn off the startup page (or customize other things)

### ISSUE THREAD

**Issue by mkaply** [duckduckgo/duckduckgo-privacy-extension#567]
## Summary
It would be great if DDG supports chrome.storage.managed to configure the extension (in particular to turn off the start page).

## Motivation
We have folks using policy to install DDG in situations where a new profile is created every time (schools) and they see the page at every startup.

## Additional context
We document how to do this for Firefox here:

https://extensionworkshop.com/documentation/enterprise/adding-policy-support-to-your-extension/

I'd be more than happy to help.

**Comment by sammacbeth** [comment]
Thanks for the suggestion! I've opened an internal ticket to discuss it with the team. 

If you have more ideas on what settings it would be useful for you to be able to control via managed storage then that would be helpful!
