### ISSUE TITLE
Cannot add localhost to whitelist

### ISSUE THREAD

**Issue by MlHsieh** [duckduckgo/duckduckgo-privacy-extension#571]
## Description

Cannot add localhost to unprotected sites.

## Steps to Reproduce

1. Open settings
2. Click `Add unprotected site`
3. Enter localhost url *127.0.0.1*
4. Click `Add`

**Expected behavior:**

Add localhost to unprotected site

**Actual behavior:**

It is considered invalid url.

**Versions**

- Extension: 2021.3.8
- Browser:  Firefox
- OS:  Windows

## Additional Information

![image](https://user-images.githubusercontent.com/61381271/111576703-f3116580-87eb-11eb-81b8-18d6206beb77.png)

**Comment by Ammako** [comment]
On Firefox, I am able to enter `localhost` as an url to add to the list. If your hosts file is configured such that `localhost` points towards `127.0.0.1`, this might work to do what you need.
