### ISSUE TITLE
getImageData massive slowdown in 2021.3.8

### ISSUE THREAD

**Issue by FizzerWL** [duckduckgo/duckduckgo-privacy-extension#574]
Hello,

Ever since the March 11th 2021 release of version 2021.3.8, I find that calling "getImageData" on a canvas is massively slower than previous versions.  Something like 150 milliseconds to return a single pixel of the canvas.

This is causing a big problem for me.  I'm the developer of a website that uses this function, and many of my users are complaining that my site runs slowly.  I figured out that every user complaining has the DuckDuckGo extension installed.  For now I'm advising them to uninstall the extension, but it'd be preferable if this problem could be resolved.

You can reproduce the problem at this url: https://www.warzone.com/SinglePlayer?Level=50 . Try zooming in then dragging around the map. You'll find it's very fast faster with the DDG extension disabled, but when enabling it it's massively slow.

**Comment by dharb** [comment]
Hi @FizzerWL, thanks for the report! We recently shipped some canvas anti-fingerprinting functionality that must be causing this, sorry about the trouble. I'm going to disable it on your website for the time being while we sort out a fix for the issue.

**Comment by dharb** [comment]
@FizzerWL we just disabled the canvas fingerprint protections on your site for the time being while we address the root issue. This change should be rolling out to all users in the next hour or so. If you continue to receive reports about this after this change is live, will you please let us know? Thanks!

**Comment by FizzerWL** [comment]
Yes, from my testing your temporary solution was successful.  Thank you so much for the prompt response!

**Comment by seeba8** [comment]
I have a similar problem on skribbl.io, I think. I recorded a performance profile in firefox: https://share.firefox.dev/3f2rEdQ

Maybe that helps pinpointing the issue.

**Comment by ChadKeating** [comment]
@dharb @jonathanKingston Please could you make this exemption for my site, my tokenstamp app is unusable with privacy essentials installed, dragging an image on to the page can make it hang forever: https://rolladvantage.com/tokenstamp/

**Comment by Yazir** [comment]
Any substantial update on this issue, at least an ETA? My I get reports of text on my phaser app (automeme.yazaa.zone) being misaligned.

**Comment by jonathanKingston** [comment]
Hey @Yazir the original issue here was finished and should be live solving the majority of the performance issues at hand here. I think it makes sense to move the phaser sizing problem to a new issue. It's the same code causing the issue but unrelated in how we would fix it. I raised https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/610 for this.
