### ISSUE TITLE
Phaser sizing issue

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/duckduckgo-privacy-extension#610]
Phaser uses canvas to detect text sizing, which with the fingerprint protection enabled returns the wrong results: https://github.com/photonstorm/phaser/issues/5625

---

...I get reports of text on my phaser app (automeme.yazaa.zone) being misaligned.

_Originally posted by @Yazir in https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/574#issuecomment-821609254_

Also: https://github.com/photonstorm/phaser/issues/5625
Related: https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/585

**Comment by jonathanKingston** [comment]
@yazir there isn't an update at present, I can reproduce the issue mentioned, I'm not sure if there is an immediate mitigation here. I can see that phaser use MeasureText code which produces an image like:
![image](https://user-images.githubusercontent.com/338988/115109438-a301fc00-9f6d-11eb-829e-1cbb962b4492.png)

The algorithm we currently use discards blank pixels but they're using red. I need to think of a way to ignore all contiguous background colours like this without reintroducing memory / performance problems like #574

**Comment by Yazir** [comment]
I see. I'd like to request a whitelist for my app then if that's a possibility.

**For phaser users stumbling upon this issue**: I have asked Phaser author about the issue and one workaround is to generate TextMetrics outside of canvas and use that for texts so positioning comes predefined, but it is a hassle to do for every text. Especially that it's to workaround issue coming from a single browser extension.

`   //  If you provide the Text Metrics in the Text Config then you can
    //  avoid it having to create a canvas, draw to it, then scan the canvas,
    //  in order to calculate the metrics internally.
    var config1 = {
        x: 100,
        y: 100,
        text: 'Phaser III',
        style: {
            fontSize: '48px',
            fontFamily: 'Arial',
            color: '#ffffff',
            metrics: {
                ascent: 45,
                descent: 10,
                fontSize: 55
            }
        }
    };

    var text = this.make.text(config1);

    //  You can get the metrics from a Text object by doing this:

    console.log(text.getTextMetrics());

    console.log(text.toJSON());`

**Comment by jonathanKingston** [comment]
> I'd like to request a whitelist for my app then if that's a possibility (automeme.yazaa.zone) .

I added the site to the override list: https://github.com/duckduckgo/content-blocking-lists/pull/18 for now.

> but it is a hassle to do for every text. Especially that it's to workaround issue coming from a single browser extension.

@Yazir for reference it's also the same for Brave and Tor users too: https://github.com/brave/brave-browser/issues/15326
