### ISSUE TITLE
brave browser crash

### ISSUE THREAD

**Issue by secchipietro04** [duckduckgo/duckduckgo-privacy-extension#618]
## Description

with the extension enabled the browser crashes if in incognito/tor if type in search bar
## Steps to Reproduce

1. step 1
enable extension in incognito tabs
2. step 2
go incognito or tor mode
3. step 3
in search tab if the text contains a space and press enter, all the tabs (even not incognito) crashes, if in tor mode everything you type makes the browser crash

**Versions**

- Extension: 2021.4.8
- Browser: brave browser (tried both beta and normal)  1.24.68
- OS:  windows 10 , in pop-os works well

**Comment by sammacbeth** [comment]
Thanks for the report. I didn't get a crash, but the search provider was broken in private windows after enabling the extension for private windows. This looks like an issue with Brave, I see they already have an issue open for it: https://github.com/brave/brave-browser/issues/15224.
