### ISSUE TITLE
Conflict with pixi.js canvas app

### ISSUE THREAD

**Issue by edzillion** [duckduckgo/duckduckgo-privacy-extension#622]
## Description
With latest version (2021.4.9) on latest FF (88.0) something is causing PIXI js graphics to be ignored. I am not sure if they are added to the canvas or not but either way they are not displayed. 

Identical objects, added from a different event, are displayed fine. 

By process of elimination I realised it was DDG privacy essentials. I see in the issues there is some kind of 'Canvas Protection' so perhaps that is where the conflict is arising. 

I am running [FoundryVTT](https://foundryvtt.com/) on localhost and there are no ads / xss or anything like that. 

## Steps to Reproduce

It's not possible for you to reproduce since I rendering the canvas through the commercial application 'foundry'. I am developing a module for that system, which uses pixi.js as its graphics renderer. But FWIW:

1. Set up a foundry game world and install the module [blood-n-guts](https://github.com/edzillion/blood-n-guts).
2. Add some actors to the scene and then damage them to trigger blood.

**Expected behavior:**
You will see two types of blood graphics: blood on the floor and blood on the actors. 

**Actual behavior:**
Only blood on the floor is displayed.  Blood on actors is missing.

**Versions**

- Extension: 2021.4.9 
- Browser: FF (88.0) 
- OS: Windows 10

## Additional Information
Never noticed this issue before, could have arisen due to some recent changes I made to the structure of the module. 

I am at a loss though - perhaps you can point out how I can work around this issue?

thanks for your time

**Comment by edzillion** [comment]
I could set up a test server to reproduce this issue and PM you the url.

Also, I tested on Chrome with the chrome extension and the problem did not occur.

**Comment by jonathanKingston** [comment]
Hi @edzillion thanks for the detailed report.

I haven't used this module myself but I have seen significant slow down in Foundry whilst using Firefox (specifically Nightly I was using) unrelated to the extension. It seems a little unlikely this would be Canvas protections given it works with the Chrome extension but let's not rule it out.

Some interesting things to try:

1. Disabling site protection in the extension browser action, this disables privacy protection like canvas changes but also blocking of external URLs
2. Checking Brave, their Canvas protection is similar.
3. Seeing in the network panel if there are external assets that are being blocked.

A URL would help certainly my email is jkingston@duckduckgo.com

**Comment by jonathanKingston** [comment]
I'm going to close this as we're still addressing canvas breakage issues but I'm happy to discuss at any time also :)
