### ISSUE TITLE
High memory on stackshare.io web site

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/duckduckgo-privacy-extension#655]
## Description
Copied over from: https://bugzilla.mozilla.org/show_bug.cgi?id=1703747

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0

## Steps to Reproduce

1. Go to: https://stackshare.io/stackups/dropwizard-vs-micronaut.

**Expected behavior:**

Memory should be properly managed.

**Actual behavior:**

Eventually my whole 32GB of memory were consumed by Firefox causing everything else to start crashing.

**Versions**

- Extension: 2021.4.9
- Browser: Firefox
- OS: Windows

**Comment by jonathanKingston** [comment]
It appears to me in Firefox the code is calling jQuery `_data` very often with what appears to be the entire DOM's nodes but it's eval'd code so finding where it's called from is a bit of a pain.
The same code never seems to fire in Chrome.

I haven't seen anything to suggest it's specific to the extension though.

**Comment by Nihal247** [comment]
Hi @jonathanKingston, I have tried to reproduce the same, with and without the extension, and I observe almost no difference in  the memory usage. I also think it's not related to the extension.
