### ISSUE TITLE
Cannot delete property 'interestCohort' of #<Document>

### ISSUE THREAD

**Issue by MonkeyDo** [duckduckgo/duckduckgo-privacy-extension#671]
## Description
Hello!
I am a developer for [ListenBrainz](https://listenbrainz.org/), and I've come to report an unhandled error that was caught in our error tracking software (Sentry).
As such I only have the information from that bug report and cannot reproduce this myself.
Here is a publicly available report of the issue: https://sentry.metabrainz.org/share/issue/9ee5a93f48724b22be1a33da59c73f2b/

## Steps to Reproduce
The error was thrown from this page: https://listenbrainz.org/user/eyepatchcheetah/recommendations

That's unfortunately all the information I have in terms of what actions the user took.

**Versions**

I unfortunately don't know either what version of the extension the user has installed, but I do have their user agent string:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.214 Safari/537.36`

Browser: Chrome v90.0.4430
OS: Windows 10

## Additional Information
The full error stack we get is this:
```
TypeError: Cannot delete property 'interestCohort' of #<Document>
  at init$5(<anonymous>:1374:26)
  at ? (<anonymous>:924:14)
  at Array.forEach(<anonymous>)
  at Object.initProtections(<anonymous>:922:26)
```

With a bit of sleuthing I tracked it back to this file: https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/7061a60629/shared/js/content-scope/floc-protection.js#L3
(at least I believe this is what's going on)

Looks like that property `interestCohort` is [non-configurable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_delete) (at least in this particular case) and cannot be deleted.

Please let me know if I can assist further in any way.

**Comment by jonathanKingston** [comment]
Hi @MonkeyDo I can confirm the assessment of the situation is correct the line you linked to is the cause of this exception.

> As such I only have the information from that bug report and cannot reproduce this myself.

I agree I can't also reproduce, how many of these calls are you seeing?

From what I can tell Chrome shouldn't make this property non configurable. It could be that the user has an extension that does this for them before the code you linked to is called.

We could fall back to attempting to override the property and catching any errors that might have been caused by other extensions the user has installed.

**Comment by jonathanKingston** [comment]
@kdzwinel I don't think there is big concern here unless we start seeing large numbers of these reports. Should we catch the error anyway?

**Comment by kdzwinel** [comment]
Thank you @MonkeyDo for letting us know, we wrapped this code in a try/catch block, this will go out with next release of the extension.

**Comment by MonkeyDo** [comment]
Nice work, that was quick !

So far we've only seen this issue from one user, but better safe than sorry!
