### ISSUE TITLE
Extension blocks access to desktop browser web app

### ISSUE THREAD

**Issue by ineuw** [duckduckgo/duckduckgo-privacy-extension#689]
## Description
The extension blocks access to pinger's textfree.us chat app for desktop browsers. I tested this in Firefox 88.0.1 and Vivaldi 3.8+, in both Windows 10 and Linux Mint 20.1

## Steps to Reproduce
1. With this extension installed and active, using either of the browsers, create a textfree account at https://messages.textfree.us/
2. Save login and password, exit and reopen the browser.

**Expected behavior:**
To be able to log in

**Actual behavior:**
I am advised to contact textfree admin and report the problem, which I did. 

**Version**
DDG 2021.5.10 in Firefox, which is my default browser.

## Additional Information
1. Repeatable.
2. My first support request about this issue was emailed to Textfree on March, 19 2021. I changed passwords, but that wasn't the problem. 

3. Are there any errors in the extension debugging console? I wouldn't know.

**Comment by sammacbeth** [comment]
Thanks for the report. I was able to reproduce an issue with logging in on this site, we'll try and figure out what's going on here and fix it!
