### ISSUE TITLE
Permission denied in audio-protection.js

### ISSUE THREAD

**Issue by austinhartzheim** [duckduckgo/duckduckgo-privacy-extension#708]
## Description
The call to `.reduce()` on `channelData` in `audio-protection.js` produces a permission denied error in Firefox 89. This prevents the audio anti-fingerprinting functionality from working on Firefox.

https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/e871aeafcd311e42996e6aadb0e52de53e38dbd1/shared/js/content-scope/audio-protection.js#L11-L13

## Steps to Reproduce

1. Open a new Firefox profile with only DuckDuckGo Privacy Essentials installed.
2. Open the developer console and execute:
```js
var ab = new AudioBuffer({length: 64, numberOfChannels: 1, sampleRate: 48000});
var abb = ab.getChannelData(0);
abb.reduce((sum, v) => {return sum + v}, 0);
```
3.Notice that the sum is zero due to `transformArrayData` returning early due to a thrown exception.

**Expected behavior:**
4. Repeat the above in Chrome. Notice that the result is non-zero due to the noise added by anti-fingerprinting.

**Actual behavior:**
5. Adding a `try`/`catch` block to log the error will display the following in the console:
```
Error: Permission denied to access object
```

**Versions**

- Extension: 2021-06-02 and Git `develop` branch.
- Browser: Firefox 89
- OS: Linux

## Additional Information

Using an alternate method to sum the values appears to work in both Firefox and Chrome. For example:
```js
let cdSum = 0;
for (var k in channelData) {
    cdSum += channelData[k];
}
```
---
Unrelated note: adding noise to a new (all-zero) `AudioBuffer ` leaks data about whether the addon is installed. For example, when the result of this JavaScript is non-zero, it's clear that noise is being added to the audio buffer:
```js
var ab = new AudioBuffer({length: 64, numberOfChannels: 1, sampleRate: 48000});
var abb = ab.getChannelData(0);
if (abb.reduce((sum, v) => {return sum + v}, 0) != 0) {
  console.log("DDG installed");
}
```

**Comment by jonathanKingston** [comment]
@austinhartzheim thanks for the report, I've fixed the issue in the PR.

I'd like to point out that a website detecting if a user has the extension installed is somewhat out of scope for us. The extension is detectable in many ways and I don't think we can circumvent this: our blocklist is unique and we have a lot of different protections that would expose the extension being installed when checking them together (EG: blocking a certain tracker + GPC + different output of canvas fingerprint per website).

So despite the canvas code filtering out blank pixels in the same nature as you are suggesting here, it's to focus on pixels with data in them and also reduce the time calculating a key.
I've ignored anything with the checksum of 0 as it's an easy carve out we can add however I'm almost certain a website could find a different Audio buffer setup that can expose us in the same manner (for example a empty buffer with one note at the end will contain noise through it once this method is applied).

**Comment by kdzwinel** [comment]
Hey Austin! Thanks again for the report and for all your thoughts about our extension that you listed on your blog. It's always great to hear a fresh perspective on our project and you are making many good points. We plan to follow them up (default # of cores, proper documentation for our protections) and we are looking forward to the "part 2" of your blogpost 🙂 If you'll have any questions about our extension please ping me directly (konrad@duckduckgo.com) and I'll connect you to the right privacy engineer that worked on given feature.

**Comment by austinhartzheim** [comment]
@jonathanKingston Thanks for getting the patch merged so quickly! I agree that fully hiding the extension isn't viable, especially with the large API surface area this extension protects - and some of the choices around how noise is added to those APIs. This probably works well against many of the fingerprinting technologies used in production, but might also leak some data when the addon is specifically targeted for fingerprinting. If you prepare a threat model document or other documentation in the future, I would recommend adding "hiding the presence of the extension" as a non-goal.

@kdzwinel Thanks for making yourself available. As you've noticed, I'm continuing to work on my analysis. I'll reach out in the future. :smile:
