### ISSUE TITLE
tablo dvr - my.tablotv.com won't won't load with DuckDuckGo Privacy Essentials

### ISSUE THREAD

**Issue by dougK44883** [duckduckgo/duckduckgo-privacy-extension#782]
## Description

When a new version was released ~Sept 2019 users of tablo TV's web app for their DVR could no longer access their tablo with out disabling DuckDuckGo.  Sure, easy enough - until they become aware of it, they believe their DVR is defective.
## Steps to Reproduce

"thing is" unless you have a networked Tablo OTA DVR you can't reproduce this :(
1. step 1  have a browser with DuckDuckGo installed - my.tablotv.com
2. step 2  notice browser behavior appears it's continuously reloads.
3. nothing ever loads.  Prior to September 2019 there wasn't an issue.

**Expected behavior:**

block trackers and load constant and stream video
**Actual behavior:**

blank page perpetually reloading
**Versions**

- Extension: 20xx-xx-xx
- 
- Browser: 
- Firefox Version 2021.7.30 | Chrome: 2021.7.30

- OS: 
- Linux

## Additional Information

Noted issues started with Release 2019-9-12  (posted in tablo community forum - https://community.tablotv.com/t/my-tablotv-com-duckduckgo-privacy-essentials/20687/2)

Although it's easy enough to disable the extension, until a user discovers this is their issue - they could be trouble shooting in various wrong directions.  My concern, it worked fine at one time.  Click on report broken site, 2yrs later users are still wondering why/how to access their DVR -- we want and need DuckDuckGO Privacy Essentials.  While being able to watch our recordings.

**Comment by jonathanKingston** [comment]
@kdzwinel this looks like it might be HTTPS upgrading based on the timelines, are you familiar with this kinda setup causing issues?

**Comment by dougK44883** [comment]
I do know the web app does not support HTTPS here's a post from TabloTV (staff) 
https://community.tablotv.com/t/problems-using-edge-browser/6917/2
>Tablo’s web app cannot use HTTPS

...so if you try https://my.tablotv.com you can't, depending upon browser and/or setting.  (Firefox tells me, Chrome just redirects and loads HTTP)

**Comment by dougK44883** [comment]
THANK YOU!
In Firefox:
`Version  2021.8.13.36133`  my.tablotv.com loads with DuckDuckGo Privacy Essentials enabled!!
And Crome as well

**Comment by jonathanKingston** [comment]
Thanks for coming back to close this out; I should have updated myself! Glad the change fixed it for you :)
