### ISSUE TITLE
Support For Pale Moon (Firefox Fork)

### ISSUE THREAD

**Issue by noellarkin** [duckduckgo/duckduckgo-privacy-extension#786]
Hey!

Thanks for the amazing work on this plugin, I've used it on Firefox and it works really well. However, I've recently shifted to Pale Moon browser (which is a fork of Firefox) and the extension isn't working on Pale Moon.

It seems that Pale Moon, and many related browsers (Basilisk, Sea Monkey, IceCat, K Meleon) use the XUL framework, as opposed to WebExtensions.

I'd really appreciate it if you could make a Pale Moon compatible plugin. I'd love to be able to continue using your plugin.

**Comment by jonathanKingston** [comment]
Hey!

Having a XUL version of the extension is unlikely to be on our timeline anytime soon; it's a significant change to the architecture for a limited audience.

Browsers are converging again further on WebExtensions:

1. https://developer.apple.com/videos/play/wwdc2021/10027/
2. https://www.w3.org/community/webextensions/2021/06/04/forming-the-wecg/

I personally think, maintaining a browser is a significant amount of work, I'm not sure we could guarantee product integrity to a browser that has limited staff maintaining it.

Thanks for your interest in DuckDuckGo and I appreciate the request. I'm going to close this but will update if anything changes in the future.
