### ISSUE TITLE
Failed detection of Firefox version

### ISSUE THREAD

**Issue by daviddoji** [duckduckgo/duckduckgo-privacy-extension#82]
I tried to install the add-on for Firefox but I got this:

    This add-on requires a newer version of Firefox (at least version 57.0). You are using Firefox 52.0.

But my system has a higher version installed:

    firefox --version
    Mozilla Firefox 57.0.4

I'm running Archlinux.

**Comment by russellholt** [comment]
Is that from the install modal on duckduckgo.com?

That is super weird. I would have said that might be our platform or version detection but that looks like it's from Firefox itself. duckduckgo.com should be returning the link to the latest if you're FF >= 57:

latest: https://addons.mozilla.org/firefox/downloads/latest/duckduckgo-for-firefox/addon-385621-latest.xpi

If we detected you are using Firefox < 57, it would return a link to a legacy API extension, which is incompatible with FF 57:

legacy: https://addons.mozilla.org/firefox/downloads/file/742979/duckduckgo_plus-1.1.26-fx.xpi

this is the direct link to the latest:

https://addons.mozilla.org/firefox/downloads/file/843471/duckduckgo_privacy_essentials-2018.1.22-an+fx.xpi

**Comment by daviddoji** [comment]
It was not from duckduckgo.com
Anyway, FF got updated yesterday and now with the link you provide, it works!
Thanks for doing this great job regarding our privacy!
