### ISSUE TITLE
Safari search bar typing issue

### ISSUE THREAD

**Issue by tylermumford** [duckduckgo/duckduckgo-privacy-extension#88]
I've been experiencing a strange bug in Safari, but only when this extension is enabled. As I type a certain phrase ("mysql returns"), the address bar is cleared and seems to reset to the address of the current page. I can reliably reproduce this, even after restarting Safari and disabling & re-enabling the extension. I think it has something to do with the speed of my typing the phrase, which suggests to me that it's an issue with asynchronous code.

After trying it on a new tab page and on google.com, when I type that phrase and the behavior is triggered, I'm actually taken to the page shown in the video (on the PHP documentation site).

Here's a [video showing the problem](https://youtu.be/AfLUnKVE-gM).

Extension version 2018.1.9, Safari 11.0.2, macOS 10.13.2, Late 2012 Mac mini. I'd be happy to provide more information if anyone wants to look into this bug further.

**Comment by russellholt** [comment]
Yeah that's interesting. Safari is sometimes preloading the top result in the background which we don't have any control over, and can result in several weird behaviors like the popup showing the preloaded site even if you haven't done anything (like push return in the address bar). Some of that seems to be completely out of our control at this moment but we're actively researching this.

**Comment by russellholt** [comment]
cc @bsstoner @jdorweiler

**Comment by davisdude** [comment]
I also experience this issue with Firefox, though it only happens when I first open a browser window. New tabs are not affected, and if you wait a few seconds the issue does not occur, so it seems like (at least in my case) it's some kind of initialization thing.

Suggested URLs don't automatically get completed like they usually do, and sometimes the search gets totally cleared.

**Comment by jdorweiler** [comment]
@tylermumford thanks for the video. It should be fixed in the most recent Safari version (2018-1-30). You might need to remove your old extension and get a new one from https://duckduckgo.com.

**Comment by jdorweiler** [comment]
@davisdude I'm seeing that too. This is the extension loading https data on start up. I think @laurengarcia was already looking into fixing that.

**Comment by tylermumford** [comment]
Great, thank you so much. On first glance, the issue appears to be fixed. I'll update this thread if I encounter it again with a newer version of the extension.
