### ISSUE TITLE
Hijacking address bar search engine in Chrome

### ISSUE THREAD

**Issue by codebudo** [duckduckgo/duckduckgo-privacy-extension#90]
The primary complaint about this extension on the [Chrome webstore 'reviews'](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg/reviews?hl=en) seems to be related to this extension forcing the user to use DDG as the default search engine in the address bar. The other feature (privacy protection, letter grading for privacy, blocking, etc.) seem to be most welcome, so these two features should be disentangled.

I received a popup asking if I would like to restore my previous search setting, but after clicking 'no' I'm no longer able to restore my previous default search settings through the extension 'options' without disabling it entirely.

Either:
  
1. Don't alter the default address bar search settings, or
1. Allow the user to restore their previous setting (either through the extension 'options' or the standard Chrome settings).

**Comment by semonje** [comment]
I'd also like an answer to this. I like the tracker blocker, letter grading, etc., but I often need the other search engines as well in other situations.

Would be nice to be able to configure this myself, preferably like one of @codebudo's proposals.

**Comment by willemavjc** [comment]
Two years later, this main complaints still remain. 

The search engine should definitely not being altered so that the default address bar search settings should remain after installing this extension; or at least, some kind of pop-up dialog should ask for a change. That would be the least.

The actual behavior is no different from Google: Are you on a personal war with them? People should remain free to choose whatever the search engine, even if this is one creepy.

Right now, you're mixing two different things: an extension about privacy and a marketshare war for search engine usage.

**Comment by willemavjc** [comment]
Okay. I managed to bypass the DuckDuckGo search engine.

Seems related to the issue [#140](https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/140) leading to a mandatory override of Chrome (or Chrome-like) settings.

How to do it:

1. **Uninstall DuckDuckGo Privacy extension**
2. **Download** the DuckDuckGo Privacy extension but **cancel the installation process** to keep the CRX file which behaves like a ZIP
3. **Unzip** the CRX file (e.g. with 7-Zip)
4. **Open** the new folder
5. Get rid of the folder `_metadata`
6. Edit the file named `manifest.json`
7. Replace the Chrome settings overrides data (line 28 as of 2020/6)
8. Go to Chrome/Chrome-like extensions manager (e.g. `edge://extensions/`)
9. Activate the `Developer mode` option
10. Click on `Load unpacked`
11. Select your uncompressed folder in step 3
12. Confirm
13. The End

Example of Chrome settings to get back to Google (Encrypted):
```
  "chrome_settings_overrides": {
    "search_provider": {
      "encoding": "UTF-8",
      "favicon_url": "https://encrypted.google.com/favicon.ico",
      "is_default": true,
      "keyword": "google.com",
      "name": "Google",
      "prepopulated_id": 92,
      "search_url": "https://encrypted.google.com/search?q={searchTerms}",
      "suggest_url": "https://encrypted.google.com/complete/search?q={searchTerms}"
    }
  },
```

**Comment by jonathanKingston** [comment]
See also: @sammacbeth's response https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/492#issuecomment-894105544 where we can't fix this.


> This is a Chrome limitation - if we want to change the default search engine on install we have to set this `is_default` flag. However, once we set this Chrome will lock the search engine choice.
> 
> There are a couple of workarounds if you want to keep the extension's privacy protections but not use our search all the time:
> 
>     1. Use our `!` bangs to redirect to different search engines when you need them
> 
>     2. Install _another_ extension that changes the default search engine, which will then unlock your search setting in Chrome.

**Comment by unuing** [comment]
Since there is a limitation, why do you still persist in setting the search engine?

**Comment by tachibana-shin** [comment]
I don't know. I thought duckduckgo would never fix this, so I created this repository fork. download the zip file from the release in my repo it won't lock your search

https://github.com/tachibana-shin/duckduckgo-privacy-extension

**Comment by unuing** [comment]
I suggest that you can show a webpage which tell the user to use ddg search engine when installing the extension, instead of force the user to use ddg.

**Comment by sammacbeth** [comment]
One of the primary purposes of this extension is to provide an easy, one-click way to switch search engine to DuckDuckGo. Doing what you suggest will make it more difficult for users to switch.

We plan to discuss with Chrome how they could improve the browser settings around search extensions, and thus fix this issue on their end.
