### ISSUE TITLE
DDG breaks `AnalyserNode.getByteFrequencyData`

### ISSUE THREAD

**Issue by brainshave** [duckduckgo/duckduckgo-privacy-extension#929]
## Description

Having DDG Privacy Extension installed breaks any calls to `AnalyserNode.getByteFrequencyData`. Looks like the culprit is missing `fingerprintingAudio` field in `exemptionLists` object when calling `shouldExemptMethod` function.

![image](https://user-images.githubusercontent.com/1305140/140854515-ed3bcf84-a54d-4391-b75f-b48a1fb67020.png)

## Steps to Reproduce

1. Install DDG Privacy Extension (no configuration changed)
2. Open a site that uses audio visualisation
   - created an example reproduction here: https://codepen.io/brainshave/pen/YzxLbVj
   - the above repro uses local microphone but doesn't send it anywhere

**Expected behavior:**

Calls to `AnalyserNode.getByteFrequencyData` return without error.

In the linked codepen above, it should say `done` in the output.

**Actual behavior:**

`AnalyserNode.getByteFrequencyData` throws an error:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at shouldExemptMethod (<anonymous>:731:31)
    at Object.outputHandler [as apply] (<anonymous>:828:31)
    at HTMLButtonElement.testButton.onclick (pen.js:17:14)
```

**Versions**

- Extension: 2021.9.30 (newest version available in Chrome store at the time of writing this)
- Browser: Chrome 95
- OS: Mac, Linux

## Additional Information

Not aware when this problem started because I don't use the extension myself. It happens every time this method is called.

**Comment by kdzwinel** [comment]
Thank you Szymon for a detailed report, we pushed out some changes to config yesterday to the config (https://github.com/duckduckgo/privacy-configuration) and must have missed that key. @jonathanKingston  is alrady on it.

**Comment by kdzwinel** [comment]
@jonathanKingston just shipped the fix, extensions check for new config every 30min, but you can force it by restarting the extension. I verified that it works as expected. Thanks again Szymon!

![looks-good](https://user-images.githubusercontent.com/985504/140897659-5bac475f-4516-4af5-9a0d-77d18fbe9916.jpg)

**Comment by brainshave** [comment]
Thank you for a quick reaction! :bow:
