### ISSUE TITLE
Potentially outdated tracker list

### ISSUE THREAD

**Issue by gunesacar** [duckduckgo/duckduckgo-privacy-extension#952]
Hi,
The Chrome and Firefox extensions seem to use a [3-year old blocklist](https://github.com/duckduckgo/duckduckgo-privacy-extension/tree/develop/shared/data/tracker_lists), while the [Safari extension reportedly uses the Tracker Radar](https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/207#issuecomment-642327424) dataset, which is more comprehensive and up-to-date.

Is that intentional, or are there [plans to switch to Tracker Radar based blocklist in the future](https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/444) for Chrome and Firefox extensions too?

Thanks so much!

**Comment by kdzwinel** [comment]
Hi @gunesacar ! All DDG apps and extensions are using same, updated monthly, blocklist based on Tracker Radar data (https://staticcdn.duckduckgo.com/trackerblocking/v2.1/tds.json). You can see it being defined here in the extension: https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/develop/shared/data/constants.js#L90 (togheter with other dynamically downloaded configs).

The folder that you referenced contains some old helper data that we still use to display some of the information in the popup. We plan to rework the popup soon.

LMK if you have any other questions.

**Comment by gunesacar** [comment]
Thank you @kdzwinel 

That makes sense. I have one further question, and please let me know if there's a better place to ask this: Why are domains such as glassboxdigital.io [present in Tracker Radar](https://github.com/duckduckgo/tracker-radar/blob/4025bc79c3c9005246efe37d53039b19e3a3f383/domains/US/glassboxdigital.io.json), but not in the [tds.json](https://staticcdn.duckduckgo.com/trackerblocking/v2.1/tds.json)?

Thanks so much again.

**Comment by kdzwinel** [comment]
Sure thing. We have certain evaluation criteria for tracker radar domains that actually end up on the blocklist (based on prevalence, fingerprinting score, cookies being set, known breakage and other fields in the dataset). This particular domain is low prevalence and non-fingerprinting so it didn't make the cut.

**Comment by gunesacar** [comment]
Thank you so much Konrad. That clarifies everything.

**Comment by kdzwinel** [comment]
Great, glad that was useful! Not sure what you are up to ;) , but feel free to ping me directly (konrad at duckduckgo.com) if you'd like to sync about any of this.

**Comment by jonathanKingston** [comment]
PR to clean up all the old fluff: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/961
